### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by WenXin20** [How-Bout-No/Outvoted#1]
`Minecraft v1.15.2`
`Forge v31.2.45`
`Outvoted vb0.2.1`

My server crashed trying to load the new update for this mod.
[Crash Report](https://gist.github.com/WenXin20/8923d4d999633f4ecfea446d0e06b0a0)

**Comment by How-Bout-No** [comment]
Weird... this crash only happens on the server and not the client, correct?

**Comment by WenXin20** [comment]
YesOn Oct 31, 2020 2:16 PM, Noah <notifications@github.com> wrote:
Weird... this crash only happens on the server and not the client, correct?

**Comment by How-Bout-No** [comment]
Apparently this is a common crash for all versions, I've narrowed down the problem and after I get a few more bugs fixed I'll push out an update on Curse.

**Comment by WenXin20** [comment]
Alright, thanks!

**Comment by How-Bout-No** [comment]
b0.2.2 is out on Curse for both 1.16.3 and 1.15.2. 1.16.1 update will be out shortly.
Please let me know if the problem persists, otherwise you are free to close this issue.
