### ISSUE TITLE
[BUG] Server crash on join with [FABRIC] Outvoted-1.5.0-beta.2. 

### ISSUE THREAD

**Issue by SplendidAlakey** [How-Bout-No/Outvoted#100]
/Before submitting, please ensure you've done the following, as these are fixes for some common bugs:
[✔] Reset/delete config files
[✔] Run without mods like Optifine (if needed)
[✔] <ins>Double check that you have the latest version!!</ins>

**Describe the bug**

When trying to join a server with [FABRIC] Outvoted-1.5.0-beta.2 installed, the server will crash.

**To Reproduce**

1. Install the mod on both sides and launch the server
2. Launch the game and try to join
3. The server will crash

**Screenshots/Logs**

[removed]

**Version (please complete the following information):**

 - Minecraft Version 1.17.1
 - Modloader Fabric 0.12.3, FAPI 0.41.0
 - Mod Version 1.5.0-b2

**Additional context**

Doesn't seem to happen in singleplayer.

I also rolled back a version to see what's the exact golem that is mentioned in the report and it's one of the 2 fully oxidized golems I spawn next to when I join the server.

**Comment by How-Bout-No** [comment]
Man I can't get a break can I 😆. I did all my testing and everything. If I had to guess maybe I didn't check for proper conversion between existing golems and the new and improved golems? I'll have to take a look once I get off work in a few hours, otherwise I'd push an emergency fix rn.

**Comment by SplendidAlakey** [comment]
No worries, happens to me all the time with testing stuff, seems like I've gone over everything and then something turns up anyway 😄 Yeah I also suspect the issue being with old (possibly only fully oxidized) golems not updating properly or something.

**Comment by How-Bout-No** [comment]
Should hopefully be fixed now in beta 3.

**Comment by SplendidAlakey** [comment]
Just tried it and joined without an issue, thank you!
