### ISSUE TITLE
[BUG] fabric 1.17.1 maxEnchantments bug

### ISSUE THREAD

**Issue by GudPiggeh** [How-Bout-No/Outvoted#101]
/Before submitting, please ensure you've done the following, as these are fixes for some common bugs:
[O ] Reset/delete config files
[ O] Run without mods like Optifine (if needed)
[ O] <ins>Double check that you have the latest version!!</ins>

**Describe the bug**
When a glutton has the max amount of enchantments stored, it will take one more enchantment from an additional item, now storing max+1 number of enchantments (observable through /data get @e[type=outvoted:glutton,limit=1,sort=nearest] Enchantments. Any item you throw in after will be immediately spit out, rendering the glutton, and the enchantments stored inside useless permanently.

**To Reproduce**
1. Throw 5 (default max) unbitten enchantments in the glutton
2. Throw a book in, showing it works
3. Throw 6 unbitten enchantments in the glutton. All items will be taken.
4. Throw any enchantable (or even unenchantable) item in. It will spit it out, and nothing in my knowledge can be done to remove them.
5. "/data get entity @e[type=outvoted:glutton,limit=1,sort=nearest] Enchantments" will show that it has 6 enchantments stored.
6. Use "/data remove entity @e[type=outvoted:glutton,limit=1,sort=nearest] Enchantments.tag.Enchantments[1]" to remove an enchantment. Now, an item can be thrown in and it will be enchanted.
 - 1.17.1
 - Fabric
 - Beta 1.5.0 3

**Comment by How-Bout-No** [comment]
Hm, seems I'm gonna have to dive back into the spaghetti that is Glutton enchanting code.

**Comment by How-Bout-No** [comment]
Should be fixed in beta 5
