### ISSUE TITLE
[BUG]Client crashes when right click the oxidized copper golem with an axe

### ISSUE THREAD

**Issue by paulzzh** [How-Bout-No/Outvoted#102]
/Before submitting, please ensure you've done the following, as these are fixes for some common bugs:
[] Reset/delete config files
[] Run without mods like Optifine (if needed)
[] <ins>Double check that you have the latest version!!</ins>

I'm playing the latest Better Minecraft [FABRIC] v17 hf.

**Describe the bug**
I'm playing SMP.I try to scrape my copper golem.The client crashes.

**To Reproduce**
1. Join a Better Minecraft server.
2. Create a copper golem.
3. Waiting for oxidation.
4. Right click the copper golem with an axe.
5. The client crashes.

**Screenshots/Logs**
![screenshot](https://user-images.githubusercontent.com/28055560/140866978-5c662bc3-d478-462b-bedd-b0b490cd2e12.png)
[crash-report](https://pastebin.com/Ku9pgips)

**Version (please complete the following information):**
 - Minecraft Version [1.17.1]
 - Modloader [Fabric]
 - Mod Version [v1.5.0-beta.3]
 - Modpack Better Minecraft [FABRIC] v17 hf

**Additional context**
I can't reproduce this in SSP.

**Comment by How-Bout-No** [comment]
Oh what? I'm surprised this wasn't fixed in the changes I did for #96. I'll look into it.

**Comment by paulzzh** [comment]
Now I can reproduce in singleplayer and multiplayer.
It's related to the gamemode.
When I'm in survival mode, the game crashes.
When I'm in creative mode, it works fine.

**Comment by How-Bout-No** [comment]
Whoops double commit. Will be fixed in beta 4.

**Comment by How-Bout-No** [comment]
Fixed in beta 4
