### ISSUE TITLE
[BUG] The glare spawns in mushroom fields

### ISSUE THREAD

**Issue by Rav10li** [How-Bout-No/Outvoted#107]
**Describe the bug**
The glare is spawning everywhere in the mushroom fields biome and i'm pretty sure this is a bug.

**To Reproduce**
1. Create a world
2. Type the command, /locate mushroom_fields
3. Teleport to the coordinates that were given
4. Notice that the glare is spawning everywhere

**Screenshots/Logs**
If applicable, add screenshots to help explain your problem, or logs from Pastebin or similar.
![Screenshot 2021-11-19 225508](https://user-images.githubusercontent.com/81896177/142717696-cfafa067-de68-4a4a-ae20-3eca36d2939a.png)

**Version (please complete the following information):**
 - Minecraft Version [1.17.1]
 - Modloader [Fabric]
 - Mod Version [1.5.0-beta.4]

**Additional context**
Add any other context about the problem here if applicable.

**Comment by How-Bout-No** [comment]
Yea safe to say that's not supposed to happen 😅. Something about this biome must mess with the light level and y level checks or something. I think I need to redo it's spawn mechanics in general.

**Comment by How-Bout-No** [comment]
Glare spawning was redone, so this issue should be solved in beta 5
