### ISSUE TITLE
[BUG] - You failed to add new Dependencies to your file page for the latest Mod Update

### ISSUE THREAD

**Issue by FatherGuse** [How-Bout-No/Outvoted#110]
Downloaded your recent update .. Crash Report listed below .. Never had a problem with your mod before, so this was a surprise .. and fwiw .. neither of these are listed as  dependencies .. and yes I have GeckoLib and Patchouli .. 

.. Might I suggest you add those API dependencies to your File Page? Might save someone else some trouble.

-- MOD outvoted --
Details:
	Mod File: outvoted-2.0.0-alpha.13.jar
	Failure message: Mod outvoted requires architectury 1.14.156 or above
		Currently, architectury is not installed
	Mod Version: 2.0.0-alpha.13
	Mod Issue URL: https://github.com/How-Bout-No/Outvoted/issues
	Exception message: MISSING EXCEPTION MESSAGE

-- MOD outvoted --
Details:
	Mod File: outvoted-2.0.0-alpha.13.jar
	Failure message: Mod outvoted requires cloth-config 4 or above
		Currently, cloth-config is not installed
	Mod Version: 2.0.0-alpha.13
	Mod Issue URL: https://github.com/How-Bout-No/Outvoted/issues
	Exception message: MISSING EXCEPTION MESSAGE

**Comment by How-Bout-No** [comment]
The dependencies are already listed on the file page (https://www.curseforge.com/minecraft/mc-mods/outvoted/files/3544511). If you were just updating the mod from alpha 12 to 13, the dependencies are the same but just newer versions.

**Comment by PhweeDev** [comment]
You're missing architectury and cloth config.

**Comment by How-Bout-No** [comment]
Closing as this isn't a bug.
If you were more asking to have *all* the dependencies listed on the main mod page, that will only really be done once either 1.5 or 2.0 gets a proper release, since only the betas/alphas use Arch and Cloth and the current main releases do not.
