### ISSUE TITLE
[URGENT BUG] - Breaking Vanilla and Modded Logs Do Not Drop 

### ISSUE THREAD

**Issue by PhweeDev** [How-Bout-No/Outvoted#111]
Version: 1.16.5, Forge - 36.2.19 (Tested on 36.2.0 aswell)
Mod Version: Outvoted 2.0.0 Alpha 13

Replication: Add mods like BYG and then Outvoted & its' dependencies. break any tree in survival mode, and you don't get any wood/logs.

**Comment by How-Bout-No** [comment]
Oof a 2.0 bug. Was this present in any earlier versions than alpha 13?

**Comment by PhweeDev** [comment]
No. it was not present in 1.16 Alpha 12. Only in 1.16 Alpha 13

**Comment by How-Bout-No** [comment]
I'm not exactly sure why this bug was caused, but I changed some stuff around and it seems to be working fine in alpha 13.1.
