### ISSUE TITLE
the great hunger crashed my game

### ISSUE THREAD

**Issue by proironik** [How-Bout-No/Outvoted#13]
The game crashed whilst rendering entity in world
Error: software.bernie.geckolib3.geo.exception.GeoModelException: outvoted:geo/hunger.geo.json: Could not find model.
Exit Code: -1
this is what it says

**Comment by How-Bout-No** [comment]
Can you post the full crash log?

**Comment by proironik** [comment]
k 1 min

**Comment by proironik** [comment]
[crash-2020-11-25_13.59.43-client.txt](https://github.com/How-Bout-No/Outvoted/files/5597896/crash-2020-11-25_13.59.43-client.txt)

**Comment by proironik** [comment]
here

**Comment by How-Bout-No** [comment]
Ok interesting. I was hoping the log gave a bit more information, but for some reason it seems as if the jar you have just doesn't have the model file for the Hunger, which it definitely should. If you try deleting both Geckolib and Outvoted and then redownload them do you still get an error?

**Comment by proironik** [comment]
Aight ill do it

**Comment by proironik** [comment]
should i download the latest update from forge or the kraken one from github

**Comment by proironik** [comment]
now no mobs are spawning, but my game isnt crashing
if there are spawn eggs for the mobs, they are not appearing in my creative menu

**Comment by How-Bout-No** [comment]
Did you make any changes to your config? Try deleting the config files and have it recreate them.
The latest version on Curse has the fixes from the GitHub so you only need to use that one.

**Comment by proironik** [comment]
before i do that
i already have a mod that lets you apply infinity and mending on a bow,
so will it interfere with the great hunger

**Comment by proironik** [comment]
and there are spawn eggs for the mobs so right

**Comment by proironik** [comment]
and this is a forge mod right

**Comment by How-Bout-No** [comment]
I haven't tested it but I don't think it should cause any issues.
Yes, there are spawn eggs for each mob.
And yes, this is for forge.

**Comment by proironik** [comment]
should i download gecko lib 3.0 beta 8 or 3.0 beta 10

**Comment by proironik** [comment]
rn i have downloaded beta 8

**Comment by proironik** [comment]
omg yes it worked

**Comment by proironik** [comment]
1 last thing, how to get higher level enchants using the great hunger

**Comment by proironik** [comment]
and the spawn rate of the mobs is configurable right cause the spawn rate of the great hunger is very high

**Comment by How-Bout-No** [comment]
Beta 10 should work fine, I've heard the full release of Geckolib 3 will be out soon.
Glad to know that fixed it!
