### ISSUE TITLE
[BUG] 2 Krakens will let u stuck and live forever if you have no range weapon underwater.

### ISSUE THREAD

**Issue by SuperPawmaple** [How-Bout-No/Outvoted#19]
Version: Latest
Forge: Forge 35.1.10

What happened.
I was attacked by two krakens at the same time. They dragged me underwater and I lost my breathe. However, I couldn't die either, I was stuck in between. Couldnt kill them cause my weapons cant reach them either. It somehow become an eternal prison. I have attached a picture to illustrate. Not sure if thats fully a bug but to some extend its weird.
![2020-12-19_22 34 50](https://user-images.githubusercontent.com/29496648/102691905-da280100-424a-11eb-8db8-7cfb540b2838.png)

**Comment by How-Bout-No** [comment]
I've had other people also complain about this. I need to find some way to prevent this. I implemented a range for how far it will chase to try and mitigate it a little, but it's obvious that the issue still occurs.
I'm not sure how to go about doing it, I have several ideas but they may be very inefficient.

**Comment by How-Bout-No** [comment]
The "not drowning" seemed to be a common issue regardless if whether or not the player was grabbed by multiple Krakens and that specific issue was solved in 219a26c, I just still need aw ay to prevent multiple Krakens from grabbing a player.

**Comment by How-Bout-No** [comment]
Fixed in b5d75ce
