### ISSUE TITLE
[Client crash] Great Hunger consumption

### ISSUE THREAD

**Issue by Cixon** [How-Bout-No/Outvoted#2]
Great Hunger crash. It occurs when it consumes more than 2 enchantment books.
Here's the log: https://pastebin.com/VXLPmRgv

Also I have another suggestion. It is if you could add a config as to how many enchantment books the great hunger can consume so people can choose.

I prefer 2 as the max and I love that the great hunger doesn't consume enchanted items. This is already fair to be honest but I know people will like to utilize the config for their mod-packs.

Thanks in advance!

**Comment by How-Bout-No** [comment]
I'm surprised I didn't find this bug in my testing, it seems like an obvious thing 😅

I've had multiple requests to add a config, so I'll be doing that shortly. It won't be next update, as there's some important bugs I need to get fixed and pushed out ASAP.

**Comment by Cixon** [comment]
> 
> 
> I'm surprised I didn't find this bug in my testing, it seems like an obvious thing 😅
> 
> I've had multiple requests to add a config, so I'll be doing that shortly. It won't be next _immediate_ update, as there's some important bugs I need to get fixed and pushed out ASAP.

sweet! cannot wait. :O

**Comment by How-Bout-No** [comment]
b0.2.2 is out which should correct this. Let me know if the issue persists, otherwise you can close this.
I'll move the config request to a separate issue for organization.
