### ISSUE TITLE
[BUG] Game crashed after trying to spawn in a mob

### ISSUE THREAD

**Issue by 1-1037** [How-Bout-No/Outvoted#22]
I was playing on Minecraft 1.15.2 with the mod version `outvoted-1.15.2-1.0.1-1.jar`.
The game suddenly freezes and crashes while I was playing, the error is as follows;
```
The game crashed whilst rendering entity in world
Error: software.bernie.geckolib3.geo.exception.GeoModelException: outvoted:geo/hunger.geo.json: Could not find model.
Exit Code: -1
```
If needed, the full crash report can be seen here;
https://pastebin.com/GJCZiNCU

**Comment by How-Bout-No** [comment]
Looks to be a similar issue to #13, I'm unsure what the actual fix was, as I recommended reinstalling the mod and geckolib, and then deleting the mod config. Not sure which one of those worked...

**Comment by How-Bout-No** [comment]
Closing this as this isn't a problem with the mod itself.
