### ISSUE TITLE
[BUG] Incompatibility with krakens and Extra Boats

### ISSUE THREAD

**Issue by HiggsBonbon** [How-Bout-No/Outvoted#23]
**Describe the bug**
When ensnared by Kraken, if the boat used is a boat with a chest, the inventory will fail to drop.

**To Reproduce**
1. Store items in an Extra Boats chest
2. Row boat near a kraken and become ensnared
3. The chest boat will enter the player's inventory but not drop any items that were stored

**Expected behavior**
The chest boat when broken normally will drop its contents and not drop as the boat with chest item.

**Version (please complete the following information):**
 - Minecraft Version 1.16.4
 - Mod Version Extra Boats 2.0.0, Outvoted 1.0.2

**Comment by How-Bout-No** [comment]
Thanks for reporting! Bug has been fixed in 2ef25cb, or v1.0.3 on Curse once the files are approved.

**Comment by How-Bout-No** [comment]
* I labeled it as a crash even though it isn't because I am very high iq.

**Comment by HiggsBonbon** [comment]
Nice work, I wasn't expecting a fix so quickly.
