### ISSUE TITLE
[BUG] Inferno "look" direction does not match head.

### ISSUE THREAD

**Issue by David2753** [How-Bout-No/Outvoted#24]
Using F3+b to examine the inferno hitbox shows that the look direction of the inferno does not match its head.
Normal vanilla mobs usually have the blue indicator perpendicular to the front of their face but the inferno's look indicator is not synced to it's head. 
Nothing game-breaking but when the inferno is on fire it looks kinda weird. It may be affecting other minor things but nothing that I've noticed

No AI Inferno (indicator to the back)
![2021-01-18_19 23 19](https://user-images.githubusercontent.com/37162792/104973869-268a6c00-59c4-11eb-89e9-319e5c55e069.png)

Offset fire (perpendicular to indicator which is offset 45 degrees from the face)
![2021-01-18_19 36 29](https://user-images.githubusercontent.com/37162792/104973990-7b2de700-59c4-11eb-93b8-a8051fd41fee.png)

**Comment by How-Bout-No** [comment]
Yea, I believe this problem occurs with all the mobs. I'd have to see if there's something I missed to have it line up, or if it's something with Geckolib (I don't have a personal reference for that).
I've seen the fire bug as well but I didn't know it was tied to that view. Odd.

**Comment by How-Bout-No** [comment]
Looks like this was Geckolib's problem. Both the look direction and subsequently the fire on the Inferno work fine in Geckolib 3.0.2.
