### ISSUE TITLE
[BUG] The Hunger causes a crash on a headless server

### ISSUE THREAD

**Issue by belathus** [How-Bout-No/Outvoted#28]
/Before submitting, please ensure you've done the following, as these are fixes for some common bugs:
[ ] Reset/delete config files
[x] Run with Java 8

**Describe the bug**
I'm hosting a server. My server crashed; it looks like the Hunger creature is trying to do something client-side only on the server.

**To Reproduce**
1. Run a headless server

**Expected behavior**
... not crash.

**Screenshots/Logs**
https://gist.github.com/belathus/14184d7d6b643238cd7b8b1656c1cec9

**Version (please complete the following information):**
 - Minecraft Version [e.g. 1.16.4 or 1.15.2]
 - Mod Version [e.g. b0.4.0]

**Additional context**
I wasn't playing on the server when this crash happened, but some other people were. I could be missing some context.

**Comment by How-Bout-No** [comment]
Interesting, it seems in the logs there's a method that it isn't finding.
Does it work if you don't run headless?

**Comment by Divineaspect** [comment]
we did just update Geckolib

**Comment by How-Bout-No** [comment]
Should be fixed in 60364f4, will be v1.1.2 on Curse once the file is approved 😄
