### ISSUE TITLE
[Server Crash] 1.16.3 Outvoted-b0.2.1

### ISSUE THREAD

**Issue by Cixon** [How-Bout-No/Outvoted#3]
**desc:** _Forge v34.1.0 server cannot launch outvoted build._

[latest.log](https://github.com/How-Bout-No/Outvoted/files/5469764/latest.log)

**Comment by How-Bout-No** [comment]
Similar to #1 but on 1.16.3. This server crash seems to affect all versions, and next update (b0.2.2) should correct it.

**Comment by How-Bout-No** [comment]
b0.2.2 is out on Curse for both 1.16.3 and 1.15.2. 1.16.1 update will be out shortly.
Please let me know if the problem persists, otherwise you are free to close this issue.
