### ISSUE TITLE
When two Great Hunger's fight each other the game crashes[BUG]

### ISSUE THREAD

**Issue by cakebaker77** [How-Bout-No/Outvoted#30]
/Before submitting, please ensure you've done the following, as these are fixes for some common bugs:
[ ] Reset/delete config files
[ ] Run with Java 8

**Describe the bug**
When you spawn in two Great Hungers they fight and when they do the game stops(crashes).

in 1.16.5

**Comment by How-Bout-No** [comment]
Is this with the latest mod version (1.1.3)?
