### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Corvus20** [How-Bout-No/Outvoted#31]
/Before submitting, please ensure you've done the following, as these are fixes for some common bugs:
[Done] Reset/delete config files
[Done] Run with Java 8

**Describe the bug**
When the Great Hunger tries to bite anything, the game crashes. Sheep, Pigs, you name it, it causes problems.

**To Reproduce**
1. Load this mod
2. Bait it into biting any mob
3. Game freezes for a moment
4. Crash occurs

**Expected behavior**
I assume it should bite the mob and deal heavy damage to/kill it. Not a crash.

**Screenshots/Logs**
[crash-2021-02-22_19.02.24-server.txt](https://github.com/How-Bout-No/Outvoted/files/6026037/crash-2021-02-22_19.02.24-server.txt)

[couldn't get pastebin to work for some reason, let me know if there's a problem with this link]

**Version (please complete the following information):**
 - Minecraft 1.16.5 Forge 36.0.40 (will try to update to newer version soon, had some issues with it in the past)
 - Mod Version: 1.1.3

**Additional context**
This could just be because of an older forge version, but figured I should at least submit this issue just in case.

**Comment by How-Bout-No** [comment]
Might be related to #30 but I haven't gotten a chance to test it yet. This only occurs on mobs and not items correct?

**Comment by How-Bout-No** [comment]
Should be fixed in 1.1.4
