### ISSUE TITLE
Great hunger kills everything when out of render. 

### ISSUE THREAD

**Issue by Lacunaethemoontraa** [How-Bout-No/Outvoted#33]
Ive been having an issue where things like farm animals and tamed mobs will be immediately killed by hunger mobs when chunks are unloaded and reloaded, or when the player moves beyond the entity render distance. 

Example: I was on an AFK platform above a creeper farm, on the ground around the farm I caught a glimpse of mobs randomly being killed immediately after spawning on the dirt area surrounding the farm several seconds later I got a death message saying that a tamed dragon of mine (wyrmroost mod) was killed by a great hunger. The dragon was placed in a pen well away from the farm and was just outside of the entity render distance. A similar occurrence happened after returning to my house after a long exploration trip, another dragon was yet again killed by one of these despite me being nowhere near it, The pen had also since been upgraded to have a non-spawnable cobble floor covered with slabs and a fully enclosed protective wall surrounding the entire farm.

This can be repeated, but it isn't the most consistent:
1. spawn an animal (preferably named) and enclose on top of a non-dirt/sand block (must be in biome where hunger spawns)
2. move upwards and away from pen and allow time to spawn (approx 120 blocks was where it happened to me)

Not entirely sure what's causing it exactly since this issue has only recently cropped up and hasn't always happened, but I would guess that there may be an issue with the checks involved with spawning the hunger in.

**Comment by How-Bout-No** [comment]
Interesting. Wasn't aware that even unloaded it still did stuff.
By recently are you saying that it has only happened recently? Which version are you running now and which version didn't have this issue?

**Comment by How-Bout-No** [comment]
Haven't been able to replicate this on my end. Not sure the cause.

**Comment by How-Bout-No** [comment]
I've pushed 1.1.6 with some modifications to Hunger spawn checking. Since I'm unable to replicate this bug, let me know if issue persists.
