### ISSUE TITLE
Use new Forge Hook for Entity Attributes

### ISSUE THREAD

**Issue by ghost** [How-Bout-No/Outvoted#34]
/Before submitting, please ensure you've done the following, as these are fixes for some common bugs:
- [x] Reset/delete config files
- [x] Run with Java 8

**Describe the bug**
just a improvement told by the output log

**To Reproduce**
1. Install mod
2. Look at the console output

**Expected behavior**
no warnings/errors

**Screenshots/Logs**
...
[HH:MM:SS] [Render thread/WARN] [ne.mi.co.ForgeHooks/]: Called deprecated GlobalEntityTypeAttributes#put for outvoted:inferno, use EntityAttributeCreationEvent instead.
[HH:MM:SS] [Render thread/WARN] [ne.mi.co.ForgeHooks/]: Called deprecated GlobalEntityTypeAttributes#put for outvoted:hunger, use EntityAttributeCreationEvent instead.
[HH:MM:SS] [Render thread/WARN] [ne.mi.co.ForgeHooks/]: Called deprecated GlobalEntityTypeAttributes#put for outvoted:kraken, use EntityAttributeCreationEvent instead.
[HH:MM:SS] [Render thread/WARN] [ne.mi.co.ForgeHooks/]: Called deprecated GlobalEntityTypeAttributes#put for supplementaries:firefly, use EntityAttributeCreationEvent instead.
...

**Version (please complete the following information):**
 - Minecraft Version 1.16.5
 - Mod Version 1.1.5

**Additional context**

**Comment by How-Bout-No** [comment]
Idk if I'd categorize this as a 'bug', just seems like a newer Forge feature. Guess I can see if I can transfer to it.
