### ISSUE TITLE
Game crash with latest Geckolib (3.0.30)

### ISSUE THREAD

**Issue by ReeCodes** [How-Bout-No/Outvoted#37]
**Describe the bug**
Look at title

**To Reproduce**
Spawn a any mob by Outvoted

**Expected behavior**
Regular behaviour

**Screenshots/Logs**
https://pastebin.com/8TFzRp4L

**Version (please complete the following information):**
 - 1.16.5
 - 1.2.2

**Comment by How-Bout-No** [comment]
Seems to be a crash thanks to the newest Geckolib version. It seems to work fine on Geckolibs prior to 3.0.30. I'll see if I can work on some fix, in the meantime I'd recommend downgrading.
