### ISSUE TITLE
[BUG] Server Crashing rending Kraken

### ISSUE THREAD

**Issue by pjlasl** [How-Bout-No/Outvoted#38]
/Before submitting, please ensure you've done the following, as these are fixes for some common bugs:
[ ] Reset/delete config files
[ ] Run with Java 8

**Describe the bug**
The server is crashing trying to render the Kraken I believe...

**Screenshots/Logs**
https://paste.ee/p/fXSi4

**Version (please complete the following information):**
 - Minecraft Version 1.16.5
 - Mod Version 1.16.5.1.2.2

**Comment by How-Bout-No** [comment]
Should already have been fixed in the latest version, 1.2.3. Please update to that.
