### ISSUE TITLE
Add a dimension blacklist/ whitelist for mob spawns

### ISSUE THREAD

**Issue by The-Bernician-Lamb** [How-Bout-No/Outvoted#39]
**Is your feature request related to a problem? Please describe.**
Recently I noticed that when trying out your mod when inside the Twilight Forest dimension that Krakens would spawn in extreme amounts whenever I was near a Twilight Lake biome. It got to the point where my game would start lagging quite severely because they would not stop spawning.

**Describe the solution you'd like**
Add a Dimension Blacklist or Whitelist for your mobs to ensure that they only spawn in their respective dimensions and to prevent them from spawning in modded dimensions and messing things up in those dimensions.

**Describe alternatives you've considered**
I've considered turning them off in the config but I quite like them and would still like them to spawn in the overworld.

**Additional context**
![2021-04-25_23 06 17](https://user-images.githubusercontent.com/64381954/116011779-bb81ae80-a61e-11eb-825e-bfe3257da06f.png)
![2021-04-25_23 37 12](https://user-images.githubusercontent.com/64381954/116011896-38148d00-a61f-11eb-98b3-c6f25c321f1b.png)

**Comment by How-Bout-No** [comment]
This is an upcoming feature in 2.0.
This spawning issue is somewhat common only in modded biomes for whatever reason. I had the same issue reported with the Jellyfishing mod's biomes. I advised them to use In Control to control mob spawns for the time being, which may work in your use case as well. It is important to note that I will have a pre release of 2.0 out sometime soon, so I'd recommend trying that out when the time comes.

EDIT: To clarify for this specific issue, it won't be a dimension-based whitelist but instead will be biome-based, but you can whitelist only biomes from specific dimensions if need be.

**Comment by How-Bout-No** [comment]
The first 2.0 snapshot with this feature is out, so I'm closing this.
