### ISSUE TITLE
Krakens can spawn in pools of water at low altitudes regardless of biome

### ISSUE THREAD

**Issue by The-Bernician-Lamb** [How-Bout-No/Outvoted#41]
**Describe the bug**
After having tested the latest Alpha version. I thought I would bring some bugs to your attention. This bug causes Krakens to spawn in any biome as long as the water it spawns in is at a low enough altitude. In vanilla this wouldn't really be a huge problem but with mods such as Yung's better caves which adds large water lakes that can generate deep underground in any biome, it becomes much more noticeable. 

**To Reproduce**
1. Start up a new world with Outvoted and Yung's better caves installed
2. Go down into the deep caves and find a region that has a water lake/ flooded caves.
3. Go into creative mode and explore these water lakes or wait near them.
4. You will see that Krakens will spawn in these underground pools/lakes despite being nowhere near an ocean.

**Expected behavior**
Krakens should only be able spawn in the ocean biomes specified in the config files and not in any low altitude water source.

**Screenshots/Logs**
Latest Log: https://gist.github.com/NJL5390/117749b9c996dcf8a7fc4511edf4eb5e

![2021-05-02_20 47 39](https://user-images.githubusercontent.com/64381954/116825931-66e3b380-ab89-11eb-9ae6-a7d059b14933.png)
![2021-05-02_20 49 32](https://user-images.githubusercontent.com/64381954/116825933-6cd99480-ab89-11eb-90c5-d28717c339ea.png)
![2021-05-02_20 38 52](https://user-images.githubusercontent.com/64381954/116826002-d063c200-ab89-11eb-9762-ed82291936e8.png)
![2021-05-02_20 37 45](https://user-images.githubusercontent.com/64381954/116826035-f6896200-ab89-11eb-8a35-c3480e07a8bb.png)

**Version (please complete the following information):**
 - Minecraft Version: 1.16.5
 - Mod Version: 2.0.0 - Alpha 1 - forge
 - Forge Version: 36.1.16

**Additional context**
They seem to even be able to spawn in the tiniest pools which is weird. It's also worth noting that I only used Yung's better caves as a way of more easily demonstrating the bug and that mod has nothing to do with the cause of it.

**Comment by How-Bout-No** [comment]
I know biome spawns are not properly functioning in alpha, but this is weird. Does it only happen in the alpha cause it could just be the biome spawning itself

**Comment by The-Bernician-Lamb** [comment]
> Does it only happen in the alpha cause it could just be the biome spawning itself

Yeah, This only happens in the Alpha, The release version is fine.

**Comment by How-Bout-No** [comment]
> Yeah, This only happens in the Alpha, The release version is fine.

Yea then it sounds like a side effect of the broken spawning. Although technically this bug should still prop up when the biome spawns are working, since the actual spawn checks are the same.

**Comment by How-Bout-No** [comment]
Biome spawning issues should be addressed in alpha.2
