### ISSUE TITLE
Krakens don't render when looking at them through water on fast or fancy graphics settings.

### ISSUE THREAD

**Issue by The-Bernician-Lamb** [How-Bout-No/Outvoted#42]
**Describe the bug**
I've noticed that sometimes whenever I looked at Krakens in the water they would just dissapear but they would still make sounds, almost like they just went invisible, when I looked away they would reappear. After changing some graphics settings I noticed that they only seemed to render properly when my graphics settings were set to Fabulous and this bug would occur often when using fast or fancy graphics settings.

**To Reproduce**
1. Start up a new world with Outvoted
2. Find a Kraken in some water near the surface or spawn one in.
3. Set graphics to fast or fancy.
4. The Kraken may disappear when you look at it. Setting graphics back to Fabulous makes them reappear.

**Expected behavior**
Krakens would render correctly through water regardless of graphics settings.

**Screenshots/Logs**
Latest Log: https://gist.github.com/NJL5390/117749b9c996dcf8a7fc4511edf4eb5e

With Fabulous Graphics settings:
![2021-05-02_20 48 40](https://user-images.githubusercontent.com/64381954/116826371-91cf0700-ab8b-11eb-8693-a19adeb701fa.png)

With Fancy graphics settings:
![2021-05-02_20 48 56](https://user-images.githubusercontent.com/64381954/116826393-a4e1d700-ab8b-11eb-9a8a-baabfab77dc1.png)

**Version (please complete the following information):**
 - Minecraft Version: 1.16.5
 - Mod Version: 2.0.0- Alpha 1 - Forge
 - Forge Version: 36.1.16

**Additional context**
This seems to occur at random but does occur quite frequently for me on these graphics settings. So I'm not sure how easy it will be to reproduce for you.

**Comment by How-Bout-No** [comment]
This might be a geckolib related issue

**Comment by The-Bernician-Lamb** [comment]
> This might be a geckolib related issue

I'm not sure, because this only seems to happen in the Alpha version of this mod and not the release version. Still, I could report it to them if you think it'll help?

**Comment by How-Bout-No** [comment]
> I'm not sure, because this only seems to happen in the Alpha version of this mod and not the release version. Still, I could report it to them if you think it'll help?

Hm are you sure it's only in alpha? I know at least that the kraken can disappear from view when looked at certain angles in the water in the normal releases. I didn't change anything with entity rendering in 2.0 alpha other than adding in the meerkat. I'll see if there's something I need to change for it to work nicely.

**Comment by The-Bernician-Lamb** [comment]
> Hm are you sure it's only in alpha?

I'll give the release version another test to make sure.

**Comment by The-Bernician-Lamb** [comment]
> Hm are you sure it's only in alpha?

EDIT: Actually, It CAN occur in the release as well but it occurs much more frequently, almost constantly in the Alpha. In the release version it only seems to occur when they are in a tight space like a cave pool or lake, and even then it seems pretty infrequent, whereas in the Alpha it happens all the time.

In the release the behaviour of this bug is far more like what you described having seen in release versions, where if you look at them at a weird angle they disappear for a bit, but only if looked at through water.  Switching to Fabulous graphics fixes this at the cost of performance, just like with the alpha version. Therefore the bugs in the alpha and release seem related to each other but the Alpha just seems to exacerbate it.

**Comment by The-Bernician-Lamb** [comment]
^^Just though I'd let you know that I updated the comment above with more information in case you are interested or haven't seen it yet. ^^

**Comment by How-Bout-No** [comment]
> EDIT: Actually, It CAN occur in the release as well but it occurs much more frequently, almost constantly in the Alpha. In the release version it only seems to occur when they are in a tight space like a cave pool or lake, and even then it seems pretty infrequent, whereas in the Alpha it happens all the time.
> 
> In the release the behaviour of this bug is far more like what you described having seen in release versions, where if you look at them at a weird angle they disappear for a bit, but only if looked at through water. Switching to Fabulous graphics fixes this at the cost of performance, just like with the alpha version. Therefore the bugs in the alpha and release seem related to each other but the Alpha just seems to exacerbate it.

Thanks for the insight. This is pretty odd, since again nothing about the rendering has been changed between release + alpha. I peeked in the Geckolib discord and apparently it is a somewhat known issue with vanilla's rendering, and fabulous changes how the rendering works and thus why the bug is fixed. I think I have an idea to remedy the issue without requiring Fabulous graphics, so I'll see what I can do for alpha.2.

**Comment by How-Bout-No** [comment]
It seems the fix I thought would work didn't :/
I'll look into it a bit further, but it's not looking like there's a whole lot I can do here.

**Comment by How-Bout-No** [comment]
Nevermind I think? It seems like the commit I made (66fbf15f7a65b3cecc9532eaf6a89d972ec8b30d) actually did fix the issue but in testing in didn't. This commit should be included in alpha.2.
