### ISSUE TITLE
Game Crashes on Startup with latest Alpha

### ISSUE THREAD

**Issue by The-Bernician-Lamb** [How-Bout-No/Outvoted#43]
**Describe the bug**
Game crashes on start up when attempting to use the latest alpha version. (Alpha 2)

**To Reproduce**
1. Attempt to start up the game with Outvoted Alpha 2 installed
2. Wait
3. Game crashes and produces the error message seen in the screenshot

**Expected behavior**
The game would start.

**Screenshots/Logs**
Latest Log: https://gist.github.com/NJL5390/4b90554182a825d529ff10210d8cc261

Screen shown when game crashes:
![2021-05-04](https://user-images.githubusercontent.com/64381954/117023156-c27c8100-acf0-11eb-9b03-055fc2dc99a9.png)

**Version (please complete the following information):**
 - Minecraft Version: 1.16.5
 - Mod Version: 2.0.0 Alpha 2 - Forge
 - Forge Version: 36.1.16

**Additional context**
No crash report is generated when the game crashes, only the error message shown in the logs and screenshot. This issue still occurs when no other mods are installed.

**Comment by How-Bout-No** [comment]
Yea this was caught pretty quickly and the file was taken down. Weird that there is no crash log, that's gonna complicate things.

**Comment by How-Bout-No** [comment]
Oh wait what? I just looked into ur latest log. Why is the Blaze mixin throwing errors? That isn't what I was expecting.

**Comment by How-Bout-No** [comment]
This bug is actually in part due to architectury, but I am still to blame for failing to test out of dev. Will need to wait for a fix before this can be re-released.

**Comment by How-Bout-No** [comment]
Fixed in Forge reupload, Fabric will be corrected later
