### ISSUE TITLE
[BUG] Outvoted crashes with Fastsuite, fastworkbench without replacement, while opening up a crafting table on dedicated server

### ISSUE THREAD

**Issue by BugmanBugman** [How-Bout-No/Outvoted#45]
/Before submitting, please ensure you've done the following, as these are fixes for some common bugs:
[x ] Reset/delete config files
[x ] Run with Java 8

**Describe the bug**
title

**To Reproduce**
1.start up dedic server
2. join it
3. craft something or open up a table
4. crash

**Expected behavior**
to craft stuff

**Screenshots/Logs**
[crash-2021-05-16_01.15.42-server.txt](https://github.com/How-Bout-No/Outvoted/files/6488769/crash-2021-05-16_01.15.42-server.txt)

**Version (please complete the following information):**
 - Minecraft Version: 1.16.5
 - Mod Version: 2.0.0 alpha 3

**Additional context**
Use it with 'fast suite' and 'fast workbench without replacement'

**Comment by How-Bout-No** [comment]
Fastsuite seems to be checking for client-only methods on the server? Seems like a simple fix though.

**Comment by BugmanBugman** [comment]
Ah ok, should i report it to fastsuite then?

**Comment by How-Bout-No** [comment]
Probably not, I can correct it on my end by just removing a line so it doesn't only run on the client. Fastsuite may be doing that for a reason, but that reason is unknown to me.

**Comment by How-Bout-No** [comment]
Will be publicly fixed in alpha 4, idk if you are able to avoid using Fastsuite until then.
