### ISSUE TITLE
Add biomedict for mob spawning

### ISSUE THREAD

**Issue by BugmanBugman** [How-Bout-No/Outvoted#46]
**Is your feature request related to a problem? Please describe.**
Sadly mobs don't spawn in modded biomes

**Describe the solution you'd like**
Making them spawn using biome dictionary, so we could get them in all the best biomes

**Comment by How-Bout-No** [comment]
Does adding the biome to the config do nothing?
i.e. `modid:biomename`?

**Comment by BugmanBugman** [comment]
I tested it on one and it works, but it would be a bit tedious for mods like BYG and BOP which have a lot of biomes, and having to add each one manually

**Comment by How-Bout-No** [comment]
Ah I see. I'll see if I can get something like that working with the current setup.

**Comment by How-Bout-No** [comment]
Essentially added into alpha 5. Use something like `#desert` to apply to all biomes categorized as a desert.
