### ISSUE TITLE
Startup Crash with Fabric Version

### ISSUE THREAD

**Issue by Blunder-G** [How-Bout-No/Outvoted#47]
Startup Crash. That's it!

How can you crash your game? (TUTORIAL)
Steps to reproduce the crash:
1. Go to Minecraft
2. Click on Play
3. Wait...
4. Crash!

Thank you for watching!

Expected behavior:
Client Crash...

Screenshots/Logs:
Crash Report: 
[crash-2021-05-24_13.31.04-client.txt](https://github.com/How-Bout-No/Outvoted/files/6531694/crash-2021-05-24_13.31.04-client.txt)

Version:
 - Minecraft 1.16.5 FABRIC
 - Outvoted-2.0.0-alpha.4-fabric

PS: **_C R A S H_**

**Comment by How-Bout-No** [comment]
Well I don't get this on my end, and this crash report isn't giving me any pointers. Are you running a curse modpack? If so which one.

**Comment by Blunder-G** [comment]
> Well I don't get this on my end, and this crash report isn't giving me any pointers. Are you running a curse modpack? If so which one.

No, i use my own pack. I don't know the reason for this crash. However, I would like to help you. What can i do?

**Comment by How-Bout-No** [comment]
Do you think you can send latest.log and/or debug.log so I can see what's going on before crash

**Comment by Blunder-G** [comment]
> Do you think you can send latest.log and/or debug.log so I can see what's going on before crash

I'm searching the mod that incompatible with Outvoted, i will find and send you ASAP :)


I foud it: xp storage mod, it's incompatible but why?
