### ISSUE TITLE
Crash upon start with "Xp Storage"

### ISSUE THREAD

**Issue by Blunder-G** [How-Bout-No/Outvoted#48]
Startup Crash with "xp storage"

Mod link: https://www.curseforge.com/minecraft/mc-mods/xp-storage

**Comment by How-Bout-No** [comment]
I see, interesting. I have no idea why this would be crashing, and the report seems to indicate it's XP Storage that is causing the crash. Odd. I'll see if there's anything I can do at my end.

**Comment by charlyb01** [comment]
Can I see the crash report?
[EDIT] Btw, where is the source of the fabric version of your mod? Or does this code work also for Fabric?

**Comment by How-Bout-No** [comment]
> Can I see the crash report?
> [EDIT] Btw, where is the source of the fabric version of your mod? Or does this code work also for Fabric?

Crash report is here 
[crash-2021-05-27_14.31.09-client.txt](https://github.com/How-Bout-No/Outvoted/files/6556219/crash-2021-05-27_14.31.09-client.txt)

Fabric code is [here](https://github.com/How-Bout-No/Outvoted/tree/architectury-dev/common/src/main/java/io/github/how_bout_no/outvoted) and [here](https://github.com/How-Bout-No/Outvoted/tree/architectury-dev/fabric/src/main/java/io/github/how_bout_no/outvoted)

**Comment by charlyb01** [comment]
Alright, thanks! I guess you can close this issue, as you said it's not related to your mod at all. I don't know yet what is going wrong while it was okay for 50k downloads before, maybe an API change. I'll let you know when it's fixed, thanks for the report =)

**Comment by How-Bout-No** [comment]
Sounds good. If there happens to be anything I need to do just lmk.
