### ISSUE TITLE
Crash Upon Startup with Terrarian Slimes

### ISSUE THREAD

**Issue by Blunder-G** [How-Bout-No/Outvoted#49]
Startup Crash

Crash Report: 
[crash-2021-05-27_22.28.48-client.txt](https://github.com/How-Bout-No/Outvoted/files/6556356/crash-2021-05-27_22.28.48-client.txt)

**Comment by How-Bout-No** [comment]
I can't seem to replicate this crash on my end? Running outvoted with terrarian slimes yields no crash.

**Comment by Blunder-G** [comment]
> I can't seem to replicate this crash on my end? Running outvoted with terrarian slimes yields no crash.

What? I guess I got paranoid after "xp storage" Sorry :l
