### ISSUE TITLE
[BUG] Palm Sapling and Baobab Sapling both render incorrectly when placed

### ISSUE THREAD

**Issue by Corvus20** [How-Bout-No/Outvoted#50]
/Before submitting, please ensure you've done the following, as these are fixes for some common bugs:
[Done] Reset/delete config files
[Done] Run with Java 8

**Describe the bug**

**To Reproduce**
1. Place down saplings
2. See the rendering (texture) errors

**Expected behavior**
The saplings should not be a transparent block with the held item sprite on each side (see screenshots below)

**Screenshots/Logs**
![2021-05-29_15 31 53](https://user-images.githubusercontent.com/75586106/120082903-95bf4d80-c093-11eb-85be-f9da74526192.png)
![2021-05-29_15 39 12](https://user-images.githubusercontent.com/75586106/120083016-09f9f100-c094-11eb-80bd-399a8b7aca21.png)

**Version (please complete the following information):**
 - Minecraft Version 1.16.5
 - Mod Version 2.0.0-alpha.5-forge

**Additional context**
I know this is an alpha release, and stuff like this is likely, but I still figured I should let you know in case you weren't aware.

**Comment by How-Bout-No** [comment]
That's uh, weird. This might be another case where I didn't set the rendering in forge (that or I just recently broke it because I know I had it fine before)

**Comment by How-Bout-No** [comment]
Seems to be the data gen isn't properly creating the jsons for the saplings. I'll just have to do them manually, will be fixed in alpha 6.

**Comment by How-Bout-No** [comment]
Fixed in alpha 6
