### ISSUE TITLE
[BUG] Fabric crash with Bewitchment

### ISSUE THREAD

**Issue by itsNordLord** [How-Bout-No/Outvoted#51]
**Versions / Loaded Mods**:
`architectury-1.15.13-fabric`
`bewitchment-1.16.5-15` BEWITCHMENT
`cloth-config-4.11.26-fabric`
`fabric-api-0.34.2+1.16`
`geckolib-fabric-1.16.5-3.0.34`
`Impersonate-2.2.1`
`outvoted-2.0.0-alpha.5-fabric` OUTVOTED
`Patchouli-1.16.4-51-FABRIC`
`Pehkui-2.2.0+21w20a`
`somnus-fabric-0.0.11-1.16.5`
`trinkets-2.6.7`

**Logs**:
[latest.log](https://github.com/How-Bout-No/Outvoted/files/6567023/latest.log)
[crash-2021-05-30_15.53.18-client.txt](https://github.com/How-Bout-No/Outvoted/files/6567024/crash-2021-05-30_15.53.18-client.txt)

**Extra**:
Curseforge is doing through a nuclear meltdown right now so I cant check if any mods have required updates, fairly certain they are up to date though. Will update the post later if necessary.

**Comment by How-Bout-No** [comment]
Yea I'd love to test this on my end but can't download any other mods lol.
Looks to be a similar error as #49 where the Wildfire isn't properly registered? I wasn't able to replicate the problem in that issue. Is this a persistent crash?

**Comment by itsNordLord** [comment]
> 
> 
> Yea I'd love to test this on my end but can't download any other mods lol.
> Looks to be a similar error as #49 where the Wildfire isn't properly registered? 

Yeah both crashlogs look pretty similar in whole

> I wasn't able to replicate the problem in that issue. Is this a persistent crash?

It is persistent, crashes 100% of the time while launching. This was tested with a completely clean instance of Fabric 0.11.3 so the configs are fresh and everything. It was replicated on a couple of used instances on different launchers as well before I decided to make a blank slate.

**Comment by How-Bout-No** [comment]
Alright once Curse fixes their apocalypse I'll see if I can narrow down the issue here.

**Comment by How-Bout-No** [comment]
Forgot to close, should be fixed in alpha 6
