### ISSUE TITLE
Crash Upon Start with Charm/Charmonium

### ISSUE THREAD

**Issue by Blunder-G** [How-Bout-No/Outvoted#52]
[crash-2021-05-31_13.08.45-client.txt](https://github.com/How-Bout-No/Outvoted/files/6569548/crash-2021-05-31_13.08.45-client.txt)

Strange...

**Comment by How-Bout-No** [comment]
I'm curious how you're running into crashes since I can't replicate it. If this is the modpack you've made can you export it and upload it here so it's easier for me to replicate your setup?

**Comment by How-Bout-No** [comment]
This kind of crash in general should be fixed in alpha 6
