### ISSUE TITLE
Add a config flag/option to disable stealing of equipped enchantments.

### ISSUE THREAD

**Issue by StormCircuit** [How-Bout-No/Outvoted#54]
**Is your feature request related to a problem? Please describe.**
I would like to disable hungers from taking enchants when they attack

**Describe the solution you'd like**
A config option to disable explicitly just their ability to 'steal' enchantments from equipped stuff.

**Describe alternatives you've considered**
Not spawning the hunger. Seems kind of lame. Looked through config files and if it's there already I apologize. I am not known for my eye sight.

**Comment by How-Bout-No** [comment]
Huh I'm surprised I didn't think of this. Will be added for alpha 8
