### ISSUE TITLE
Crash on Kraken visual range

### ISSUE THREAD

**Issue by VallenFrostweaver** [How-Bout-No/Outvoted#56]
**Describe the bug**
Crash on approaching a Kraken.

- Minecraft Version 1.16.5
- Outvoted 1.2.1
- Forge 36.1.2

**Additional context**
Multiple other mods are installed. I cannot determine the source of the crash. If this is not the mod causing the crash, I would appreciate any knowleddge you can share as to what one may be causing the issue. I am more than happy to supply other info if it would be helpful.

Pastebin crash report here: https://pastebin.com/WwrrCfbf

**Comment by How-Bout-No** [comment]
The latest non alpha of Outvoted is 1.2.4. Can you try using that and see if it still crashes?

**Comment by VallenFrostweaver** [comment]
Strange that the launcher I was using did not report that mod as having an update available.  Sorry, I usually update everything before reporting. I have now updated to 1.2.4 and it no longer persists. Thank you.
