### ISSUE TITLE
[BUG - Fabric - 1.17] - Loot Table for blocks is missing

### ISSUE THREAD

**Issue by StellaBiscuit** [How-Bout-No/Outvoted#57]
/Before submitting, please ensure you've done the following, as these are fixes for some common bugs:
[ ] Reset/delete config files
[ ] Run with Java 8

**Describe the bug**
The Loot Table of EVERY SINGLE block is missing

**To Reproduce**
1. Open the mod itself with WinRar or a similar app
2. Go to "data/outvoted/loot_tables"
3. See that there is no "block" folder meaning there is no loot table for the blocks
Bonus - 4. Ingame, every block from the mod gives nothing 

**Expected behavior**
Quite obvious
I want to obtain my blocks

**Screenshots/Logs**
Inside the loot_tables folder
![image](https://user-images.githubusercontent.com/53101126/125506062-7cc0a216-43fc-48da-b764-5f4ebba755be.png)

**Version (please complete the following information):**
 - Minecraft Version [e.g. 1.17 - Fabric]
 - Mod Version [2.0.0-alpha.8]

**Additional context**
None

**Comment by How-Bout-No** [comment]
Man how much stuff changed from 1.16 to 1.17 😩
I'll see if there's something it wants me to add or if I need to do something different with the jsons.

**Comment by StellaBiscuit** [comment]
Hum... the folder with the loot tables for the blocks is straight up inexistant... that is the problem, the blocks don't even have a drop in the first place

**Comment by How-Bout-No** [comment]
I assume I botched something in Architectury, as Forge 1.17 isn't out yet so this upgrade was a shot in the dark. Will be fixed.

**Comment by How-Bout-No** [comment]
Should be fixed in alpha 9
