### ISSUE TITLE
outvoted 1.17.1 isn't downloading

### ISSUE THREAD

**Issue by Myle21** [How-Bout-No/Outvoted#58]
/Before submitting, please ensure you've done the following, as these are fixes for some common bugs:
[ ] Reset/delete config files
[ ] Run with Java 8

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots/Logs**
If applicable, add screenshots to help explain your problem, or logs from Pastebin or similar.

**Version (please complete the following information):**
 - Minecraft Version [e.g. 1.16.4 or 1.15.2]
 - Mod Version [e.g. b0.4.0]

**Additional context**

**Comment by How-Bout-No** [comment]
You uh... didn't fill out the issue template. I have no information on the issue.

**Comment by Myle21** [comment]
sorry, in 2021 my dumb ass wasn't able to comprehend github.
