### ISSUE TITLE
Geckolib 3.0.1 not detected

### ISSUE THREAD

**Issue by SirOMGitsYOU** [How-Bout-No/Outvoted#6]
**Describe the bug**

**To Reproduce**
1. install gecko 3.0.1 Beta01/02
2. Install outvoted
3. Crash

**Expected behavior**
No crash & detect mod

**Screenshots/Logs**
[crash-2020-11-05_23.25.53-fml.txt](https://github.com/How-Bout-No/Outvoted/files/5497998/crash-2020-11-05_23.25.53-fml.txt)

**Version (please complete the following information):**
 - Minecraft Version 1.16.3
 - Mod Version b0.2.3

**Additional context**
Unsure if this is an issue with Outvoted not detecting geckolib 3.0.1 or a geckolib issue.

**Comment by How-Bout-No** [comment]
Geckolib 3.0.0 is quite different than 2.x.x as it changes how animations are made/used, so it's not as simple as just updating to the newest version. As 3.0.0 is still in beta, I haven't begun updating the models, animations, and/or code related to it, but I will be at some point.

**Comment by SirOMGitsYOU** [comment]
Ah I see okay, I’ll try get my client working with the version 2.

**Comment by How-Bout-No** [comment]
Closing this now, #8 was created to track 3.0.0 update and will be closed once implemented.
