### ISSUE TITLE
[BUG, FABRIC 1.17.1, 2.0.0-alpha.9]

### ISSUE THREAD

**Issue by Tyropop** [How-Bout-No/Outvoted#60]
https://pastebin.com/EE0kG88K

this happens a soon as i open the game

**Comment by How-Bout-No** [comment]
I can't replicate this issue, but some surface investigation leads me to believe that one of the mods, Cardinal Components, seems to be outdated. Whether it's bundled with some other mod or not, could you try installing this version and let me know if the issue persists? https://www.curseforge.com/minecraft/mc-mods/cardinal-components/files/3397538

**Comment by How-Bout-No** [comment]
Closing as above solution should fix the problem. Reopen if otherwise.
