### ISSUE TITLE
[BUG] Mob noises audible with no volume dropoff on distance

### ISSUE THREAD

**Issue by Seegras** [How-Bout-No/Outvoted#64]
Mob noises are audible from quite far away at maximum volume. Which makes it impossible to detect where exactly they are, and also an extreme nuisance, especially with meerkats. 

**Version (please complete the following information):**
 - Minecraft Version [1.17.1]
 - Mod Version [2.0.0-alpha.9-fabric]

**Comment by How-Bout-No** [comment]
I have tweaked all of the sounds to have a more consistent volume in the latest alphas.
