### ISSUE TITLE
[BUG] Wildfire takes falling damage

### ISSUE THREAD

**Issue by Ahdie1** [How-Bout-No/Outvoted#69]
That's it, it takes damage when slowly floating down, unless the blaze which does not. Unless this was intentional.

**Comment by How-Bout-No** [comment]
Oh that's... weird. Just like a lone of code or 2 was missing. Easy fix.

**Comment by How-Bout-No** [comment]
The code for handling fall damage is already in the Wildfire (which I already assumed, especially since I used the Blaze code as a template) and testing shows that it works fine as it always has. How did you manage to get the Wildfire to take fall damage?

**Comment by How-Bout-No** [comment]
Closing as this shouldn't be an issue.
