### ISSUE TITLE
[BUG] Palm and Baobab tree bugs

### ISSUE THREAD

**Issue by 1-1037** [How-Bout-No/Outvoted#73]
For both the trees when you break the leaves in survival, with any tool (including fist) you get the leaves back instead of saplings.

Baobab saplings won't produce a tree, even with bone meal.

Minecraft Version 1.17.1
Mod Version v2.0.0-alpha.12
Fabric Version 0.11.6

**Comment by 1-1037** [comment]
I also forgot to add, there are no "generic" crafting recipes for either wood. (can't craft sticks, chests, crafting tables, etc.)

**Comment by How-Bout-No** [comment]
Huh... the leaves drop table should be about the same as vanilla (as I used vanilla methods to create it) but perhaps I glossed over something. Same with the other recipes not working.
Baobab saplings need to be in a 4x4 arrangement due to their sheer size. A single sapling or 2x2 won't work.

**Comment by 1-1037** [comment]
I did try with the 4x4 initially, but after a couple of minutes of trying it didn't work, though that could just be me.

**Comment by How-Bout-No** [comment]
Fixed in latest alpha
