### ISSUE TITLE
[BUG] Players randomly crashing

### ISSUE THREAD

**Issue by NebulaBC** [How-Bout-No/Outvoted#75]
/Before submitting, please ensure you've done the following, as these are fixes for some common bugs:
[ ] Reset/delete config files
[ ] Run with Java 8

**Describe the bug**
Randomly, players on my All of the Fabric 4 server will crash, sometimes at the same time, sometimes at a separate time. There does not appear to be any output in console besides Disconnected.

**To Reproduce**
1. Install a All of the Fabric 4 server
2. Play on it regularly

**Expected behavior**
Server should run fine, and client should not crash

**Screenshots/Logs**
A log from my client: https://bytebin.lucko.me/ZrHAShdpct

**Version (please complete the following information):**
 - Minecraft Version 1.17.1 All of the Fabric 4
 - Mod Version 2.0.0-alpha.11-fabric

**Comment by How-Bout-No** [comment]
Sorry I got to this really late, the log link seems to be invalid. Could you reupload it if you're still experiencing the issue?

**Comment by How-Bout-No** [comment]
Closed due to no response.
