### ISSUE TITLE
[BUG] Glutton spawn issues

### ISSUE THREAD

**Issue by Muffintiem** [How-Bout-No/Outvoted#76]
This is a lower priority bug since it doesn't crash the game or anything but in custom biomes sometimes the wrong Gluttons are spawning. Like I'm finding swamp Gluttons in desert biomes.

**Comment by How-Bout-No** [comment]
What version is this on?

**Comment by Muffintiem** [comment]
Most recent one for Fabric 1.17.1. Alpha 12 I think.
