### ISSUE TITLE
[BUG] Ostrich saddle causing crash.

### ISSUE THREAD

**Issue by Muffintiem** [How-Bout-No/Outvoted#77]
In the 1.17.1 Alpha 12 version of Outvoted I got a crash when I tried putting a saddle on a tamed Ostrich.

https://pastebin.com/k7R1xWjV

**Comment by How-Bout-No** [comment]
Seemed to be some minimal change in maybe a Geckolib version or Fabric itself. Should be fixed in next build. I'd recommend using the latest Geckolib and Fabric API when the time comes.

**Comment by Muffintiem** [comment]
Idk why but any version of Geckolib past 3.0.10 causes my game to be stuck in a loadloop. Everything else worked fine so I just stuck with the earlier version. Maybe it's time for me to go let them know something is up.
