### ISSUE TITLE
Kraken spawns en masse in twilight forest. (kinda lols)

### ISSUE THREAD

**Issue by hacktheplanet86** [How-Bout-No/Outvoted#79]
So I was exploring the TF in creative mode and noticed a big lake, which are kind of rare in that dimension.  I was kind of surprised to see what was spawning in it..... (Edit to add version: 1.16.5-1.2.4
![krakenslol](https://user-images.githubusercontent.com/89303901/131902965-52ea04b0-20b7-47ce-8c03-29952ed1e1a8.png)

**Comment by How-Bout-No** [comment]
Yes modded biomes cause issues, afaik there isn't much for me to do about that. If need be, you could use a mod like In Control to adjust spawn rates.
