### ISSUE TITLE
NPE

### ISSUE THREAD

**Issue by klugemonkey** [How-Bout-No/Outvoted#80]
/Before submitting, please ensure you've done the following, as these are fixes for some common bugs:
[ ] Reset/delete config files - but why?
[ ] Run with Java 8 - wait, i can run 1.17.1 on Java 8?,  hmm time to update bug report format.

**Describe the bug**
NPE: missing null pointer check on o.github.how_bout_no.outvoted.entity.BarnacleEntity.getTargetedEntity()

**To Reproduce**
1. play a pack, wait several days, and maybe it will occur.

**Expected behavior**
check for null pointer and avoid crashing the client.

**Screenshots/Logs**
---- Minecraft Crash Report ----
// I feel sad now :(

Time: 9/6/21, 1:31 AM
Description: Rendering entity in world

java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1309.method_19538()" because the return value of "io.github.how_bout_no.outvoted.entity.BarnacleEntity.getTargetedEntity()" is null
	at io.github.how_bout_no.outvoted.entity.BarnacleEntity.predicate(BarnacleEntity.java:541)
	at software.bernie.geckolib3.core.controller.AnimationController.testAnimationPredicate(AnimationController.java:487)
	at software.bernie.geckolib3.core.controller.AnimationController.process(AnimationController.java:357)
	at software.bernie.geckolib3.core.processor.AnimationProcessor.tickAnimation(AnimationProcessor.java:65)
	at software.bernie.geckolib3.model.AnimatedGeoModel.setLivingAnimations(AnimatedGeoModel.java:78)
	at io.github.how_bout_no.outvoted.client.model.BarnacleModel.setLivingAnimations(BarnacleModel.java:32)
	at io.github.how_bout_no.outvoted.client.model.BarnacleModel.setLivingAnimations(BarnacleModel.java:13)
	at software.bernie.geckolib3.renderers.geo.GeoEntityRenderer.render(GeoEntityRenderer.java:154)
	at software.bernie.geckolib3.renderers.geo.GeoEntityRenderer.method_3936(GeoEntityRenderer.java:41)
	at net.minecraft.class_898.method_3954(class_898.java:135)
	at net.minecraft.class_761.method_22977(class_761.java:1482)
	at net.minecraft.class_761.method_22710(class_761.java:1230)
	at net.minecraft.class_757.method_3188(class_757.java:1026)
	at net.minecraft.class_757.method_3192(class_757.java:810)
	at net.minecraft.class_310.method_1523(class_310.java:1112)
	at net.minecraft.class_310.method_1514(class_310.java:728)
	at net.minecraft.client.main.Main.main(Main.java:217)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at io.github.how_bout_no.outvoted.entity.BarnacleEntity.predicate(BarnacleEntity.java:541)
	at software.bernie.geckolib3.core.controller.AnimationController.testAnimationPredicate(AnimationController.java:487)
	at software.bernie.geckolib3.core.controller.AnimationController.process(AnimationController.java:357)
	at software.bernie.geckolib3.core.processor.AnimationProcessor.tickAnimation(AnimationProcessor.java:65)
	at software.bernie.geckolib3.model.AnimatedGeoModel.setLivingAnimations(AnimatedGeoModel.java:78)
	at io.github.how_bout_no.outvoted.client.model.BarnacleModel.setLivingAnimations(BarnacleModel.java:32)

-- Patchouli Book Info --
Details:
	Patchouli open book context: n/a
Stacktrace:
	at net.minecraft.class_128.handler$ekh000$fillPatchouliContext(class_128.java:521)
	at net.minecraft.class_128.<init>(class_128.java:37)
	at net.minecraft.class_128.method_560(class_128.java:267)
	at net.minecraft.class_898.method_3954(class_898.java:156)
	at net.minecraft.class_761.method_22977(class_761.java:1482)
	at net.minecraft.class_761.method_22710(class_761.java:1230)
	at net.minecraft.class_757.method_3188(class_757.java:1026)
	at net.minecraft.class_757.method_3192(class_757.java:810)
	at net.minecraft.class_310.method_1523(class_310.java:1112)
	at net.minecraft.class_310.method_1514(class_310.java:728)
	at net.minecraft.client.main.Main.main(Main.java:217)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

-- Entity being rendered --
Details:
	Entity Type: outvoted:barnacle (io.github.how_bout_no.outvoted.entity.BarnacleEntity)
	Entity ID: 953897
	Entity Name: Barnacle
	Entity's Exact location: 361.17, 44.39, -72.70
	Entity's Block location: World: (361,44,-73), Section: (at 9,12,7 in 22,2,-5; chunk contains blocks 352,-64,-80 to 367,319,-65), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,-64,-512 to 511,319,-1)
	Entity's Momentum: 0.06, -0.05, 0.05
	Entity's Passengers: []
	Entity's Vehicle: null

-- Renderer details --
Details:
	Assigned renderer: io.github.how_bout_no.outvoted.client.render.BarnacleRenderer@1c77996e
	Location: 69.42,-12.21,-78.58 - World: (69,-13,-79), Section: (at 5,3,1 in 4,-1,-5; chunk contains blocks 64,-64,-80 to 79,319,-65), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,-64,-512 to 511,319,-1)
	Rotation: 127.96875
	Delta: 0.554307

-- Affected level --
Details:
	All players: 1 total; [class_746['klugemonkey'/678245, l='ClientLevel', x=291.80, y=55.00, z=5.78]]
	Chunk stats: 1024, 576
	Level dimension: minecraft:overworld
	Level spawn location: World: (16,89,-208), Section: (at 0,9,0 in 1,5,-13; chunk contains blocks 16,-64,-208 to 31,319,-193), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,-64,-512 to 511,319,-1)
	Level time: 2467101 game time, 3007499 day time
	Server brand: fabric
	Server type: Non-integrated multiplayer server

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Excalibur_V1.16, STONEBORN - 1.17 - V2.1.zip, EmbellishedStone-1.17.1.zip, Skyrim Soundpack v5.7.zip, Fabric Mods, KubeJS Resource Pack [assets]

-- System Details --
Details:
	Minecraft Version: 1.17.1
	Minecraft Version ID: 1.17.1
	Operating System: Linux (amd64)  -redacted-
	Java Version: 16.0.2, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 5612884632 bytes (5352 MiB) / 8589934592 bytes (8192 MiB) up to 13421772800 bytes (12800 MiB)
	CPUs: 12
	Processor Vendor: GenuineIntel
	Processor Name:  -redacted-
	Identifier:  -redacted-
	Microarchitecture:  -redacted-
	Frequency (GHz):  -redacted-
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name:  -redacted-
	Graphics card #0 vendor:  -redacted-
	Graphics card #0 VRAM (MB): 288.00
	Graphics card #0 deviceId: 0x13f1
	Graphics card #0 versionInfo: unknown
	Memory slot #0 capacity (MB): 16384.00
	Memory slot #0 clockSpeed (GHz): -0.00
	Memory slot #0 type: DDR3
	Memory slot #1 capacity (MB): 16384.00
	Memory slot #1 clockSpeed (GHz): -0.00
	Memory slot #1 type: DDR3
	Memory slot #2 capacity (MB): 16384.00
	Memory slot #2 clockSpeed (GHz): -0.00
	Memory slot #2 type: DDR3
	Virtual memory max (MB): 73185.06
	Virtual memory used (MB): 24181.14
	Swap memory total (MB): 49076.00
	Swap memory used (MB): 0.00
	JVM Flags: 2 total; -Xms8192m -Xmx12800m
	Fabric Mods: 
		additionaladditions: Additional Additions 2.1.2
		additionalbars: Additional Bars 2.1.1
		advanced_runtime_resource_pack: Runtime Resource Pack 0.2.9
		advancementplaques: Advancement Plaques 1.4.0
		advancements-enlarger: Advancements Enlarger 0.2.4
		adventurez: AdventureZ 1.2.11
		amecsapi: Amecs API 1.1.5+mc21w16a
		aqupdcaracal: Caracal mob 1.17-1.3.11
		aqupdgrizzly: Grizzly Bear mob 1.17-1.2.0
		arcanus: Arcanus 1.7
		architects_palette: Architect's Palette Fabric 1.2
		architectury: Architectury 2.5.27
		artifality: Artifality 0.3.4
		assembly: Assembly 21w06a-1.0.0
		attributefix: Attribute Fix {FABRIC} 1.0.3
		awokenworld: Awoken World 1.0.1
		axolotlitemfix: Axolotl Item Fix 1.1.2
		backslot: BackSlot 1.2.0
		backslotaddon: BackSlot Addon 1.0.6
		barrenisles: Barren Isles fabric-1.17-1.0.6
		bclib: BCLib 0.3.1
		betterend: Better End 0.11.0-pre
		betterf3: BetterF3 1.1.5
		bettermineshafts: YUNG's Better Mineshafts 1.17-1.0.1
		betternether: Better Nether 5.1.3
		bettersodiumvideosettingsbutton: Better Sodium Video Settings Button 2.0.1
		betterstrongholds: YUNG's Better Strongholds 1.17-1.1.1
		betterthirdperson: Better Third Person 1.5.0
		bewitchment: Bewitchment 1.17-5
		biomeinfo: Biome Info 1.17-7
		caelus: Caelus API 0.0.17-1.17
		cardinal-components: Cardinal Components API 3.1.1
		cardinal-components-base: Cardinal Components API (base) 3.1.1
		cardinal-components-block: Cardinal Components API (blocks) 3.1.1
		cardinal-components-chunk: Cardinal Components API (chunks) 3.1.1
		cardinal-components-entity: Cardinal Components API (entities) 3.1.1
		cardinal-components-item: Cardinal Components API (items) 3.1.1
		cardinal-components-level: Cardinal Components API (world saves) 3.1.1
		cardinal-components-scoreboard: Cardinal Components API (scoreboard) 3.1.1
		cardinal-components-util: Cardinal Components API (utilities) 3.1.1
		cardinal-components-world: Cardinal Components API (worlds) 3.1.1
		carrier: Carrier 1.8.0
		caves-and-cliffs-add-on-for-william-wythers-overhauled-overworld: Caves and Cliffs add-on for William Wythers Overhauled Overworld 1.3
		charm: Charm 3.3.2
		charmonium: Charmonium 3.3.0
		cherishedworlds: Cherished Worlds 2.0.1-1.17.1
		cleancut: CleanCut 1.17-4.0-fabric
		cleardespawn: Clear Despawn 1.17.1-fabric0.36.1-1.1.1
		cloth-api: Cloth API 2.0.54
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-client-events-v0: Cloth Client Events v0 2.0.54
		cloth-common-events-v1: Cloth Common Events v1 2.0.54
		cloth-config2: Cloth Config v5 5.0.38
		cloth-datagen-api-v1: Cloth Datagen v1 2.0.54
		cloth-scissors-api-v1: Cloth Scissors API v1 2.0.54
		cloth-utils-v1: Cloth Utils v1 2.0.54
		colytra: Colytra 2.0.0-1.17
		com_electronwill_night-config_core: core 3.6.3
		com_electronwill_night-config_toml: toml 3.6.3
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		com_velocitypowered_velocity-native: velocity-native 1.1.0-SNAPSHOT
		comforts: Comforts 0.0.6-1.17.1
		conjuring: Conjuring 1.0.7
		controlling: Controlling For Fabric 1.1.2
		couplings: Couplings 1.5.0+1.17
		cozy_camping: Cozy Camping 1.0.0-1.17
		croptopia: Croptopia 1.6.1
		crowdin-translate: CrowdinTranslate 1.3+1.17
		customportalapi: Custom Portals 0.0.1-beta33-1.17
		darkpaintings: Dark Paintings 4.0.2
		dawn: Dawn API 2.0.6
		deepslatecutting: Deepslate Cutting 1.2.0
		disable_custom_worlds_advice: Disable Custom Worlds Advice 1.3
		dragonloot: DragonLoot 1.0.9
		drinkbeer: Drink Beer 2.1
		dual_riders: DualRiders 1.0.5
		dungeons_arise: When Dungeons Arise 2.1.47-fabric
		dynamicfps: Dynamic FPS 2.0.5
		dynmus: Dynamic Music 1.3.1
		earthtojavamobs: Earth2Java 1.7.3+1.17
		eldritch_mobs: Eldritch Mobs 1.9.2
		elytratrinket: Elytra Trinket 2.0.1-1.17
		enchantment_lore: EnchantmentLore 1.2.1+MC1.17.1
		endrem: End Remastered 4.1.0
		enhanced_attack_indicator: Enhanced Attack Indicator 1.0.2+1.17
		enhanced_mushrooms: Enhanced Mushrooms 1.0.5
		enhancedcelestials: Enhanced Celestials 2.0.4
		environmentz: EnvironmentZ 1.1.5
		fabric: Fabric API 0.40.0+1.17
		fabric-api-base: Fabric API Base 0.3.0+a02b446313
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.3.0+cbda931818
		fabric-biome-api-v1: Fabric Biome API (v1) 3.2.0+cbda931818
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.5+a02b446318
		fabric-command-api-v1: Fabric Command API (v1) 1.1.3+5ab9934c18
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+92519afa18
		fabric-containers-v0: Fabric Containers (v0) 0.1.12+cbda931818
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.3.0+cbda931818
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.5+be9da31018
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.11+6cefd57718
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.2.3+87cc6e4c18
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.10+fc40aa9d18
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+92519afa18
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.7+cbda931818
		fabric-item-api-v1: Fabric Item API (v1) 1.2.4+a02b4463d5
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.10+b7ab612118
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.4+cbda931818
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.2+36b77c3e18
		fabric-language-kotlin: Fabric Language Kotlin 1.6.4+kotlin.1.5.30
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.4+a02b44633d
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.4+a02b446318
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+92519afa18
		fabric-models-v0: Fabric Models (v0) 0.3.0+a02b446318
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.13+cbda931818
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.11+a02b446318
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+92519afa13
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.10.9+b7ab6121d5
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.3+a02b446318
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+a02b446318
		fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.10+e2961fee18
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.4+cbda931818
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.8+cbda931818
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.2+fc40aa9d18
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+a02b446313
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.13+a02b446318
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.3+fc40aa9d18
		fabric-rendering-v1: Fabric Rendering (v1) 1.8.1+fc40aa9d18
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.8+a00e834b18
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.4+cbda931818
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.8+cbda931818
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.13+5ab9934c18
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.2.1+b06cb95b18
		fabric-textures-v0: Fabric Textures (v0) 1.0.6+a02b446318
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.12+b7ab6121d5
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.3.0+fc40aa9d18
		fabric-tree-chopper: Fabric Tree Chopper 0.7.2
		fabricloader: Fabric Loader 0.11.6
		fallingleaves: Falling Leaves 1.7.3+1.17.1
		fancymenu: FancyMenu 2.2.2
		fermion: Fermion 2.11.241
		fermion-modkeys: Fermion Modifier Keys 1.10.241
		ferritecore: FerriteCore 3.0.3
		fiber: fiber 0.23.0-2
		fiber2cloth: Fiber To Cloth 3.2.0
		firstperson: FirstpersonModel 2.0.2
		flesh2leather: Flesh2Leather 1.0.2
		flintytools: Flinty Tools 1.0.0
		flytre-lib-base: Flytre Lib - Base Module 1.2.0
		flytre-lib-compat: Flytre Lib - Compat Module 1.0.0
		flytre-lib-config: Flytre Lib - Config Module 1.1.0
		flytre-lib-event: Flytre Lib - Event Module 1.0.1
		flytre-lib-gui: Flytre Lib - GUI Module 1.0.0
		flytre-lib-storage: Flytre Lib - Storage Module 2.3.1
		flytre_lib: Flytre Lib 1.3.7
		forgottenrecipes: Forgotten Recipes 1.0.2
		gateofbabylon: Gate Of Babylon 1.5.0-1.17
		gbfabrictools: GBfabrictools 1.3.4+1.17
		geckolib3: Geckolib 3.0.13
		gobber2: Gobber2 2.4.41
		grass_pass: Grass Bypass 1.0.0
		graveyard: The Graveyard 1.0
		harvest_scythes: Harvest Scythes 2.0.6
		hologram-api: Hologram API 0.2.1+1.17.1
		horsestatsvanilla: Horse Stats Vanilla 4.1.8
		icarus: Icarus 1.3
		illuminations: Illuminations 1.7
		impaled: Impaled 1.0.1
		impersonate: Impersonate 2.3.3
		inmis: Inmis 2.3.1-1.17
		interactic: Interactic 0.1.5-1.17
		inventoryhud: Inventory HUD + 3.4.0
		iris: Iris 1.1.1
		jankson: Jankson 3.0.1+j1.2.0
		java: OpenJDK 64-Bit Server VM 16
		kanos_config: Kanos Config 0.1.4+1.14.4-1.17.1
		kirin: Kirin UI 1.9.1
		konkrete: Konkrete 1.2.3
		krypton: Krypton 0.1.4
		kubejs: KubeJS 1605.3.10-build.9999
		lacrimis: Lacrimis 2.1.3+1.17.1
		lazydfu: LazyDFU 0.1.2
		levelz: LevelZ 1.0.5
		libcd: LibCapableData 3.0.3+1.16.3
		libgui: LibGui 4.1.6+1.17.1
		libninepatch: LibNinePatch 1.1.0
		lithium: Lithium 0.7.4
		lovely_snails: Lovely Snails 1.0.3+1.17
		magicfungi: Magic Fungi 0.3.0-BETA+1.17.1
		mavm: More Axolotl Variants Mod 1.0.3a
		maybe-data: Maybe data 1.0.1-1.17
		me_hypherionmc_simple-rpc-lib: simple-rpc-lib 2.1.5
		megane: megane 5.2.1
		megane-base: megane-base 5.2.1
		megane-fabric-transfer: megane-fabric-transfer 5.2.1+1.1.0-3fe74aa118
		megane-runtime: megane-runtime 5.2.1
		megane-vanilla: megane-vanilla 5.2.1+1.17.1
		minecraft: Minecraft 1.17.1
		mm: Manningham Mills 2.3
		modmenu: Mod Menu 2.0.0-beta.7
		more-structures-add-on-for-william-wythers-overhauled-overworld: More Structures add-on for William Wythers Overhauled Overworld 1.2
		morerespawnanchors: More Respawn Anchors 1.0.2
		morevillagers-fabric: MoreVillagersFabric 2.0.4-SNAPSHOT
		mostructures: Mo' Structures 1.3.0-pre1-1.17.1
		mousewheelie: Mouse Wheelie 1.7.3+mc1.17.1-pre1
		multi_item_lib: Multi Item Lib 1.4.0
		mythic-mounts: Mythic Mounts 1.17.1-1.2
		namepain: Name Pain 1.4.0
		naturescompass: Nature's Compass 1.17.1-2.0.1-fabric
		nears: Nears 1.1.2
		nearsightedly: Near-Sightedly 1.2.1
		netherite_items: Netherite Items 1.1.0
		notenoughanimations: NotEnoughAnimations 1.3.0
		npcvariety: NPC Variety 2.1.2
		omega-config: OmegaConfig 1.0.8
		onsoulfire: On Soul Fire 1.17-3
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.5.30
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.5.30
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.5.30
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.5.30
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.5.1
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.5.1
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.2.2
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.2.2
		outvoted: Outvoted 2.0.0-alpha.12
		owo: OwO 0.1.1
		oxidized: Oxidized 1.3.0
		oxidizelib: OxidizeLib 1.1.0
		packet_tweaker: Packet Tweaker 0.2.0-1.17-pre1
		patchouli: Patchouli 1.17-54-FABRIC
		paxi: Paxi 1.17-1.2.2
		pehkui: Pehkui 2.3.0+1.14.4-1.17.1
		pigsteel: Pigsteel Mod 1.6.6
		placeholder-api: Placeholder API 1.1.0+1.17.1
		playerabilitylib: Pal 1.3.0
		polymer: Polymer 0.1.0-rc.4+1.17.1
		polymorph: Polymorph 0.0.12-1.17.1
		presencefootsteps: Presence Footsteps r32-1.17-rc1
		primordial-shores-add-on-for-wwoo: Primordial Shores add-on for William Wythers Overhauled Overworld 1.0
		promenade: Promenade 2.1.2
		pugh_lib: Pugh Lib ${version}
		pugh_tools: Pugh Tools ${version}
		quartzelv: Quartz Elevator 1.2.5
		ratsmischief: Rat's Mischief 1.2.2
		reach-entity-attributes: Reach Entity Attributes 2.1.1
		realisticfirespread: Realistic Fire Spread 1.17-3
		repurposed_structures: Repurposed Structures 2.3.2+1.17.1
		rhino: Rhino 1605.1.2-build.40
		roughlyenoughitems: Roughly Enough Items 6.0.279-alpha
		rpgdifficulty: Rpg Difficulty 1.0.7
		runelic: Runelic 3.0.1
		scorch: Scorch 1.1.0
		seasons: Fabric Seasons 1.2.2-BETA+1.17
		seedy-behavior: Seedy Behavior 1.0.1
		server_translations_api: Server Translations API 1.4.5+1.17
		sgui: SGui 1.0.0-rc4+1.17.1
		shulkerutils: shulkerutils 1.0.4-1.17
		simple-rpc: Simple Rpc 1.17-2.3.1-fabric
		sit: Sit 1.17.1-13
		snowundertrees: Snow Under Trees 1.0.0
		sodium: Sodium 0.3.0+IRIS2
		somnus: Somnus API 0.0.14-1.17.1
		spark: spark 1.6.1
		staffofbuilding: Staff of Building 1.3.2-1.17
		static-content: Static Content 1.0.1-1.16.2
		staticdata: Static Data 1.1.2
		step-height-entity-attribute: Step Height Entity Attribute 1.0.0
		stoneholm: Stoneholm 1.3
		stonevaults: Stonevaults 1.1.0
		sulfurpotassiummod: Sulfur & Potassium 1.1.1
		talking-villagers: Talking Villagers 1.1.3
		terraform-biome-builder-api-v1: Terraform Biome Builder API (v1) 2.0.0
		terraform-config-api-v1: Terraform Config API (v1) 2.0.0
		terraform-overworld-biome-extensions-api-v1: Terraform Overworld Biome Extensions API (v1) 2.0.0
		terraform-shapes-api-v1: Terraform Shapes API (v1) 1.0.4
		terraform-surfaces-api-v1: Terraform Surfaces API (v1) 2.0.0
		terraform-tree-api-v1: Terraform Tree API (v1) 2.0.0
		terraform-wood-api-v1: Terraform Wood API (v1) 2.0.2
		the_aether: The Aether 1.17.1-1.5.0
		things: Things 0.2.5
		totemicoverhaul: Totemic Overhaul 1.1.7
		transliterationlib: TRansliterationLib 1.1.0
		traverse: Traverse 4.0.0-beta.2
		trinkets: Trinkets 3.0.3
		tweed: Tweed 3.0.0-beta.26
		universal-graves: Universal Graves 1.0.8+1.17.1
		upgradedechests: Upgraded Ender Chests 1.0.2-1.17
		upgradedshulkers: Upgraded Shulkers 1.0.2-1.17
		urns: Urns 1.0.1
		vanilla_degus: Vanilla Degus 1.2.0
		veinmining: Vein Mining 0.0.10-1.17
		villagernames: Villager Names 2.0.0
		villagershats: Goosik's Villager Hats 1.2.0
		voidtotem: Void Totem (Fabric) 1.17.0-1.0.0
		voidz: VoidZ 1.0.5
		wandering_collector: Wandering Collector 1.0.2+mc1.17
		waystones: Waystones 2.0.4
		william-wythers-overhauled-overworld: William Wythers Overhauled Overworld 1.6
		wolveswitharmor: Wolves With Armor 1.6.0-1.17
		woods_and_mires: Woods and Mires 1.1.1+1.17
		wrenchable: Wrenchable 1.1.0+1.17
		wthit: wthit 3.8.1
		xaerominimap: Xaero's Minimap 21.14.0
		xaeroworldmap: Xaero's World Map 1.15.0.1
		xps: Xp Obelisk 0.1.9_for_1.17.x_Fabric
		yungsapi: YUNG's API 1.17-Fabric-16
	Launched Version: MultiMC5
	Backend library: LWJGL version 3.2.2 build 10
	Backend API:  -redacted-
	Window size: 1920x1080
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, file/Excalibur_V1.16 (incompatible), file/STONEBORN - 1.17 - V2.1.zip, file/EmbellishedStone-1.17.1.zip, file/Skyrim Soundpack v5.7.zip (incompatible)
	Current Language: English (United Kingdom)
	CPU:  -redacted-

**Version (please complete the following information):**
 - 1.17.1
 - 2.0.0-alpha.12

**Additional context**
stuff happens.  did say alpha, so meh.

**Comment by How-Bout-No** [comment]
Same as #67 I believe but this time the crash is mapped, which is neat. iirc I have this fixed in dev but not in a public build yet.

**Comment by How-Bout-No** [comment]
(Also, for the bug report template, a lot of config changes happened early in dev so I always recommended resetting the configs to reduce variables. Same with running with Java 8 because, also early on, newer versions of Java were incompatible.)

**Comment by Muffintiem** [comment]
Just curious when is the ETA on the next public build?

**Comment by How-Bout-No** [comment]
> Just curious when is the ETA on the next public build?

I don't like to set ETAs, maybe in the next day or 2 as of writing?

**Comment by How-Bout-No** [comment]
Should be fixed in latest alphas. Reopen if problem persists.
