### ISSUE TITLE
[BUG] Crashing due to barnacle nullpointer

### ISSUE THREAD

**Issue by SoggyDiaperz** [How-Bout-No/Outvoted#81]
/Before submitting, please ensure you've done the following, as these are fixes for some common bugs:
[ ] Reset/delete config files
[ ] Run with Java 8

**Describe the bug**
I received occasional crashes that the log blames on the barnacle entity, but after reloading the game it seems fine.

**To Reproduce**
Not sure as it happened randomly

**Expected behavior**

**Screenshots/Logs**
If applicable, add screenshots to help explain your problem, or logs from Pastebin or similar.
http://hastebin.com/vapinokoqu.yaml

**Version (please complete the following information):**
 - Minecraft Version [e.g. 1.16.4 or 1.15.2]
 - Mod Version [e.g. b0.4.0]
 -
 - Fabric 1.17.1

**Additional context**

**Comment by How-Bout-No** [comment]
Already should be fixed in latest alphas. Unless it's not. Are you running alpha 13?

**Comment by SoggyDiaperz** [comment]
Oh sorry, seems I was using alpha 12. Thanks for updating!
