### ISSUE TITLE
[BurrowGenFeature]

### ISSUE THREAD

**Issue by Nebula240** [How-Bout-No/Outvoted#82]
**Describe the bug**
The server is randomly crashing, log points to "BurrowGenFeature"

**To Reproduce**

**Expected behavior**

**Screenshots/Logs**
https://pastebin.ubuntu.com/p/YFmTXktGxH/
https://pastebin.ubuntu.com/p/ncmXyQG4tJ/

**Version (please complete the following information):**
 - Minecraft Version 1.16.5 Forge
 - Mod Version 1.2.4

**Comment by How-Bout-No** [comment]
Does this only happen on the server?

**Comment by Nebula240** [comment]
As far as I've seen, yes. 
No reports on this bug on singleplayer in the modpack discord nor the issues tab so yes, only in the server

**Comment by How-Bout-No** [comment]
I see. I'll take a look at it when I get the chance.

**Comment by Nebula240** [comment]
Thanks

**Comment by InteJason** [comment]
Receiving many reports about this in my modpack as well: https://pastebin.com/5zqFgNxe

**Comment by How-Bout-No** [comment]
I've made a quick [dev jar](https://cdn.discordapp.com/attachments/776261854514905102/886703811387871272/outvoted-2.0.0-alpha.12.1-forge.jar) that may fix this error. Only needed on the server side and not in any public releases atm.

**Comment by Hachuurui** [comment]
I'll put it in my server to test if that's ok @How-Bout-No ?

**Comment by Hachuurui** [comment]
This jar appears to have fixed the issue. Thank you so much!

**Comment by How-Bout-No** [comment]
Good to hear. I don't have time to package a proper release at the moment but will try to get this more public once I've confirmed it doesn't break anything.

**Comment by InteJason** [comment]
any ETA on this going public? It seems to be quite a common crash

**Comment by How-Bout-No** [comment]
Should be fixed in alpha 14
