### ISSUE TITLE
barncale spawn causing crash[BUG]

### ISSUE THREAD

**Issue by kevins88** [How-Bout-No/Outvoted#84]
/Before submitting, please ensure you've done the following, as these are fixes for some common bugs:
[ ] Reset/delete config files
[ ] Run without mods like Optifine (if needed)
[ ] <ins>Double check that you have the latest version!!</ins>

**Describe the bug**
i have been playing on this map for a week now and all the sudden when it tried to spawn in the first barnacle of the day  it crashed. i was using alpha 12 but i updated to alpha 13 and same issue

**To Reproduce**
1. Go to 'deep ocean'
2. Click on 'find barnacle '
3. Scroll down to ''

**Screenshots/Logs**
https://pastebin.com/VS84PxDL

**Version (please complete the following information):**
 - Minecraft Version [e.g. 1.16.4 or 1.17.1]
 - Modloader [e.g. Forge or Fabric]
 - Mod Version [e.g. 1.2.4 or alpha.12]

**Additional context**

**Comment by How-Bout-No** [comment]
The issue template is here for a reason -.-
Use the latest version, should be fixed in alpha 13

**Comment by How-Bout-No** [comment]
Sorry, read this wrong. If this crash still happens in alpha 13 can you post the crash log with that version?

**Comment by kevins88** [comment]
the paste bin crash report i posted was with the alpha 13

**Comment by How-Bout-No** [comment]
No it says you had alpha 12 installed in the pastebin.
