### ISSUE TITLE
Random crash BarnacleEntity

### ISSUE THREAD

**Issue by Twosiders** [How-Bout-No/Outvoted#85]
`The game crashed whilst rendering entity in world
Error: java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1309.method_19538()" because the return value of "io.github.how_bout_no.outvoted.entity.BarnacleEntity.getTargetedEntity()" is null
Exit Code: -1`

Might be the same as 
https://github.com/How-Bout-No/Outvoted/issues/84

**Comment by Twosiders** [comment]
[crash-2021-09-22_12.44.53-client.txt](https://github.com/How-Bout-No/Outvoted/files/7210029/crash-2021-09-22_12.44.53-client.txt)
Attached crash log.
Cannot attach world unfortunately for some unknown reason GitHub is not telling me. Probably too large.

**Comment by Twosiders** [comment]
I've had the barnacle spawn and attack me multiple times beforehand near the shore, without a problem. 
This time it caused a crash it seems. I was on land, around 30 blocks from the ocean.

**Comment by How-Bout-No** [comment]
As I said in the other issue, this bug should already be fixed in alpha 13 so please update.
