### ISSUE TITLE
[BUG] Mob spawn configuration is not functional.

### ISSUE THREAD

**Issue by jadeitemods** [How-Bout-No/Outvoted#87]
/Before submitting, please ensure you've done the following, as these are fixes for some common bugs:
[ ] Reset/delete config files **I don't know how to do this, or if they will at all help.**
[ ] Run without mods like Optifine (if needed) **My server's modpack does not run with Optifine.**
[ ] <ins>Double check that you have the latest version!!</ins> **I use the most recent version, the 1.17.1 beta release.**

**Describe the bug**
I wanted to make the wildfire and lurker spawn in less biomes (for context, I use a mod menu mod that allows me to configure mods I have installed in the server). So I set them to only spawn in one biome each, in their respective dimensions. And yet, both of them are spawning in other biomes. I can't keep the wildfire in Nether wastes, and I can't keep the lurker/kraken in deep frozen oceans.

**To Reproduce**
1. Go to 'https://www.curseforge.com/minecraft/mc-mods/modmenu/files'. This is where I grabbed the mod menu. Download the 1.17.1 version.
2. Boot up the game and go to the mod menu, and from there locate Outvoted.
3. Click on 'Entities' and then 'Barnacle'|'Wildfire'. Then 'Spawn Biomes'.
4. I deleted all of the ones it normally shows up in, and replaced it with 'minecraft:deep_frozen_ocean'|'minecraft:nether_wastes'. Both examples met stunning failure. The most obvious is about eight encounters in soulsand valleys and other Nether biomes my server peoples have had with wildfires.

**Screenshots/Logs**
If applicable, add screenshots to help explain your problem, or logs from Pastebin or similar.

**Version (please complete the following information):**
 - Minecraft Version [e.g. 1.16.4 or 1.17.1] **1.17.1.**
 - Modloader [e.g. Forge or Fabric] **Fabric.**
 - Mod Version [e.g. 1.2.4 or alpha.12] **Beta release.**

**Additional context**
Additionally, the wildfire helmet is missing its top texture.
I made this report to see if maybe this was all just incomplete features due to the fact that it's only a beta release?

**Comment by How-Bout-No** [comment]
If you use mod menu to change mod config, you're only changing the client config. You can't modify server configs from in-game so that has to be done manually in the server config folder.

**Comment by jadeitemods** [comment]
Ah, thank you.
