### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by lilrichy** [How-Bout-No/Outvoted#89]
**Describe the bug**
Outvoted book is placed in inventory every time a user logs into server. I looked in configs and it dosnt seem to be an option to turn book off on login.

**To Reproduce**
Log out of server and log back in. Get a new book each time. Should only get book on first login.

**Version (please complete the following information):**
 - Minecraft Version  1.17.1
 - Modloader  Fabric
 - Mod Version 2.0.0-alpha.11

**Additional context**
I don't know if this is an issue with this mod or with the mod pack im playing which is All of Fabric 4.

**Comment by Nebula240** [comment]
Not only happens on Fabric, happens on forge too. 

There are people who have 2 chests filled with nothing than the book 🤣

**Comment by lilrichy** [comment]
Maybe implementing the give book to new users like how it is described at 
https://vazkiimods.github.io/Patchouli/docs/patchouli-basics/giving-new 
instead of the current way it is being implemented. 
Although I have found the config option to disable the book at login "givePatchouliBookOnLogin": false I must of missed it when I first looked. 
This stops the issue however it still should not spam the book more than once so it is still a bug in my opinion. But I guess this can be closed if this is the intended behavior.

**Comment by How-Bout-No** [comment]
> Maybe implementing the give book to new users like how it is described at https://vazkiimods.github.io/Patchouli/docs/patchouli-basics/giving-new instead of the current way it is being implemented. 

I was actually unaware of this, hence the faulty method being used currently. I'll just migrate to the way it's outlined there. Thank you!

> Although I have found the config option to disable the book at login "givePatchouliBookOnLogin": false I must of missed it when I first looked. This stops the issue however it still should not spam the book more than once so it is still a bug in my opinion. But I guess this can be closed if this is the intended behavior.

The config name is kinda vague but no it's not intended to give the book at *every* login.

**Comment by How-Bout-No** [comment]
Fixed in alpha 14, but due to using advancements the config option isn't functional, so that will need to be fixed if possible.

**Comment by How-Bout-No** [comment]
Config check fixed in the 1.5 betas, will be merged into 2.0 alphas after release.
