### ISSUE TITLE
[1.16.4] Cannot launch minecraft using b0.3.1

### ISSUE THREAD

**Issue by Cixon** [How-Bout-No/Outvoted#9]
**Describe the bug**
Cannot load beta 0.3.1 on Forge [35.0.7].

**Steps to reproduce the behavior:**
1. Use Forge [35.0.7]
2. Launch Minecraft
3. See error

**Expected behavior**
Successful load. No errors.

**Screenshots/Logs**
![Screenshot (473)](https://user-images.githubusercontent.com/69068153/98777371-35e2ad00-23b6-11eb-872c-75ca9dff0886.png)

[latest.log](https://github.com/How-Bout-No/Outvoted/files/5522232/latest.log)
[debug.log](https://github.com/How-Bout-No/Outvoted/files/5522233/debug.log)

**Version:**
 - Forge 1.16.4 [35.0.7]
 - Version: b0.3.1

**Additional context**
Using Java 14 {C:\Program Files\Java\jdk-14.0.2\bin\javaw.exe}.
Also using a mod that changes how minecraft handles its boot up. [LINK](https://www.curseforge.com/minecraft/mc-mods/smooth-boot/files/3107849)

**Comment by How-Bout-No** [comment]
Odd, I can't replicate this on my end (although I haven't tested Java 14). Does this issue still occur on the latest 1.16.4 forge? (35.0.15 as of writing)

**Comment by Cixon** [comment]
> 
> 
> Odd, I can't replicate this on my end (although I haven't tested Java 14). Does this issue still occur on the latest 1.16.4 forge? (35.0.15 as of writing)

Fixed in v3.1.2. Thanks!

**Comment by How-Bout-No** [comment]
Interesting, I didn't even change anything related in that version, lol.

**Comment by Gunner76th** [comment]
It should be noted that Java 8 should be used for all Modded Minecraft instances. Versions of Java 9-15 generally do not work properly and are therefore not advised at present. Until official word comes directly from the Forge team, only use Java 8.
