### ISSUE TITLE
[BUG] can't disable the book in the latest fabric version

### ISSUE THREAD

**Issue by Chuunkyz** [How-Bout-No/Outvoted#92]
well, everything is in the title, i don't know if the whole config is broken, but i still get the book when i join the world if i disable it in the config

**Comment by How-Bout-No** [comment]
Yes because of the switch to advancements for giving books the config won't work easily and I need to find some way to adapt that (if even possible). The good news is in this case it should only ever give out one per user per world.

**Comment by malice936** [comment]
Unfortunately this doesn't hold true for the 1.16.5 version which has given me the book 4 times now every time I load my world, otherwise very pleased with the mod.

**Comment by How-Bout-No** [comment]
> Unfortunately this doesn't hold true for the 1.16.5 version which has given me the book 4 times now every time I load my world, otherwise very pleased with the mod.

Yes, 1.16.5 hasn't received an update yet. The Fabric was a silent launch since it was small.

**Comment by How-Bout-No** [comment]
Fixed in beta 4
