### ISSUE TITLE
[BUG] Some doors and trapdoors look identical

### ISSUE THREAD

**Issue by Rav10li** [How-Bout-No/Outvoted#93]
/Before submitting, please ensure you've done the following, as these are fixes for some common bugs:
[ ] Reset/delete config files
[ ] Run without mods like Optifine (if needed)
[ ] <ins>Double check that you have the latest version!!</ins>

**Describe the bug**
The Palm Door looks like the Jungle Door and the Baobab Door looks like the Acacia Door.
**To Reproduce**
1. Go into creative '...'
2. Grab Baobab Door and Acacia Door  '....'
3. Place them '....'
4. Notice how they are identical

**Screenshots/Logs**
If applicable, add screenshots to help explain your problem, or logs from Pastebin or similar.
![image](https://user-images.githubusercontent.com/81896177/138186140-4242e16f-5e0f-44bd-89ef-23f18bd1e893.png)

**Version (please complete the following information):**
 - Minecraft Version [1.17.1]
 - Modloader [Fabric]
 - Mod Version [outvoted-2.0.0-alpha.14-fabric]

**Additional context**
I just checked after posting and I'm editing to let you know that this is happening to all baobab and palm items except for logs and wood.

**Comment by How-Bout-No** [comment]
Duplicate #72. Palm and Baobab do not have unique textures as of right now.
