### ISSUE TITLE
[Request] stop gluttons fighting creepers

### ISSUE THREAD

**Issue by supersaiyansubtlety** [How-Bout-No/Outvoted#94]
**Is your feature request related to a problem? Please describe.**
Gluttons (at least the swamp variety) fight creepers, and the creepers explode. This causes random explosions around the world wherever both can spawn. 

**Describe the solution you'd like**
It'd be great if this behavior were removed or an  option to disable it were added. 

**Additional context**
I'm using Fabric on MC 1.17.1, and the creeper x glutton fight occurred in a [Woods and Mires](https://modrinth.com/mod/woods-and-mires) Mire biome, which counts as a swamp.

**Comment by How-Bout-No** [comment]
Implemented in the 1.5 betas, will be migrated to 2.0 alphas after.
