### ISSUE TITLE
[BUG] The guide book can't be obtained on [FABRIC] Outvoted-1.5.0-beta.1

### ISSUE THREAD

**Issue by SplendidAlakey** [How-Bout-No/Outvoted#95]
/Before submitting, please ensure you've done the following, as these are fixes for some common bugs:
[✔] Reset/delete config files
[✔] Run without mods like Optifine (if needed)
[✔] <ins>Double check that you have the latest version!!</ins>

**Describe the bug**

When trying to craft an Outvoted guide book by combining a lava bucket with a book, no output is given. The book also fails to be given on spawn. It also doesn't exist in the /give command output. The only way I found to obtain the book was with some of my mods (I'm not sure which ones, because I have so many of them), that allow you to see unobtainable items in the creative inventory. However, the book itself is broken.

**To Reproduce**

1. Install Fabric API, Architectury, Cloth config, GeckoLib and Outvoted
2. Launch the game and create a new world or enter an old one
3. No guide book is given on spawn
4. Try to craft the book by combining a lava bucket and a book and see that there's no output

**Screenshots/Logs**

[removed]

Broken book:
![2021-10-25_20 50 56](https://user-images.githubusercontent.com/86702831/138753140-09fc528b-cfd8-476a-ba55-e2d452629222.png)
![2021-10-25_20 51 00](https://user-images.githubusercontent.com/86702831/138753151-eb985671-24b1-476e-ba2d-fc8d8756cfa0.png)

**Version (please complete the following information):**

 - Minecraft Version 1.17.1
 - Modloader Fabric 0.12.3, FAPI 0.41.0
 - Mod Version 1.5.0-b1

**Additional context**

Tested the issue without any other mods loaded, apart from FAPI and Outvoted's dependencies.

**Comment by How-Bout-No** [comment]
Oh... odd. I guess that's one thing I missed, since in dev it's always broken but outside of dev it always seemed to work. Will work on a fix.

Edit: It actually looks like 2.0 patchouli entries are in 1.5, hoping that's the only reason it's broken...

**Comment by How-Bout-No** [comment]
Book issues should be fixed in beta 2, at least on new logins players are given a book and the book opens without problems.

Also, due to the way Patchouli works (or maybe the way I'm using Patchouli) the command to give a book would be `/give whoever patchouli:guide_book{"patchouli:book": "outvoted:book"}` as the book is dependent on Patchouli and not it's own unique item within the mod, if that makes sense.
