### ISSUE TITLE
[BUG] Copper button is missing a recipe

### ISSUE THREAD

**Issue by SplendidAlakey** [How-Bout-No/Outvoted#98]
/Before submitting, please ensure you've done the following, as these are fixes for some common bugs:
[✔] Reset/delete config files
[✔] Run without mods like Optifine (if needed)
[✔] <ins>Double check that you have the latest version!!</ins>

**Describe the bug**

Copper button is missing its recipe, making it unobtainable in survival.

**To Reproduce**

1. Unlock all recipes and use the crafting book or use REI to look up a copper button recipe
2. Find out that the recipe is missing <sub><sub> and cry </sub></sub>

**Screenshots/Logs**

![2021-10-26_17 03 15](https://user-images.githubusercontent.com/86702831/138908932-ca880a22-f77e-4d7a-832a-258c778a21f5.png)

**Version (please complete the following information):**

 - Minecraft Version 1.17.1
 - Modloader Fabric 0.12.3, FAPI 0.41.0
 - Mod Version 1.5.0-b1 / [1.5.0-b2](https://github.com/How-Bout-No/Outvoted/issues/96#issuecomment-951349576)

**Additional context**

Tested without any mods present as well.

**Comment by How-Bout-No** [comment]
Don't know *how* I missed this but I realized shortly after release that the recipes were gone. Will be corrected in beta 2.

**Comment by How-Bout-No** [comment]
Recipes are somewhat fixed in beta 2. The only discrepancy is that single Copper Blocks already have a recipe that converts it into ingots. Currently the only way to get a normal Copper Button is either use a mod that allows multiple recipes from the same items (can't remember the name but ik it's out there) or craft an Exposed/Weathered/Oxidized Copper Button and scrape it with an axe. Not intuitive, I'll see if I can do something about that, but for now the recipes are working.

**Comment by SplendidAlakey** [comment]
The mod is called [Polymorph](https://www.curseforge.com/minecraft/mc-mods/polymorph-fabric).

Also grabbing recipes from REI works, if I choose ingots I get ingots, if I choose the button, I get the button.

**Comment by How-Bout-No** [comment]
> Also grabbing recipes from REI works, if I choose ingots I get ingots, if I choose the button, I get the button.

Interesting. I'd rather try and avoid recipe conflicts, especially ones that clash directly with vanilla recipes. In beta 3 I've redone the recipes where 1 Copper Ingot = 1 Copper Button and removed the recipes for the oxidization stages.
