### ISSUE TITLE
[BUG-1.17.1] Crash when clicking an item related to the Barnacle in JEI. (WITH JEI Resources addon.)

### ISSUE THREAD

**Issue by Gbergz** [How-Bout-No/Outvoted#99]
**Describe the bug**
Clicking an item related to the Barnacle in JEI makes the game flash white stupidly fast then crash.

**To Reproduce**
1. Install Outvoted + GeckoLib & JEI & JEI Resources.
2. Show uses related to a Barnacle item.
3. Game starts to flash uncontrollably (rip eyes).
4. Crash.

**Screenshots/Logs**
https://gist.github.com/Gbergz/aa0de0bbce8f6dce7aa6fc150f4f0b4e
![image](https://user-images.githubusercontent.com/26634554/139290697-829465f2-c2c6-4dec-b085-a4320cdb76fc.png)

**Version (please complete the following information):**
 - Minecraft Version [1.17.1]
 - Modloader [Forge]
 - Mod Version [1.5.0-b2] | https://www.curseforge.com/minecraft/mc-mods/outvoted/files/3507504
 - Geckolib version [3.0.5]

**Comment by How-Bout-No** [comment]
Oh wow, sorry your eyes had to get destroyed. Did this happen in beta 1 at all? And does it only happen with the Barnacle?

**Comment by Gbergz** [comment]
I'll get back you with an answer to that when I am home !

**Comment by Gbergz** [comment]
Yep, it still happens on Beta 1

**EDIT:** Here's a GIF on the situation. Just left-clicking the Barnacle Tooth in JEI.
https://gyazo.com/356996ae20f6ee628a7cb3fdbc11362b

**Comment by How-Bout-No** [comment]
> Yep, it still happens on Beta 1
> 
> **EDIT:** Here's a GIF on the situation. Just left-clicking the Barnacle Tooth in JEI. https://gyazo.com/356996ae20f6ee628a7cb3fdbc11362b

Oh wow yea that's awful. Really confused on what the hell might be causing that, I'll have to do some digging tomorrow.

**Comment by BugmanBugman** [comment]
Got crash from the Barnacle too 
https://crashy.net/SUfNSwP5oiyRqy0I0MXr

**Comment by How-Bout-No** [comment]
I've figured out *where* it crashes code-wise but I can't determine *why* it's crashing, for whatever reason it just isn't finding a method that should be there. Will be fixed next beta.
